### ISSUE TITLE
[Request]: Python Scripting API

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1082]
### Problem

There is not a clear way to develop features for people who not familiar with the large codebase.

### Solution

I would like to see the ability to write python scripts using an API provided by Yim to create new features for the menu.

### Reason

Python is a simple language, easy to use, and can interact with the C++ codebase.

### Additional context

This would also allow for much more extensive development because a lot of people could develop scripts and features for the menu

**Comment by GeopJr** [comment]
I doubt this is going to happen. Python is pretty big in size and does not come pre-installed on windows so the only option is requiring users to install it themselves.

Instead, lua (#83) or wren (#488) are more appropriate.

**Comment by Rxann** [comment]
Alright, should i change the request title and content?

**Comment by Yimura** [comment]
No, keep it like this, others that'll search for this should be able to read the original context.

In regards to adding a scripting API of some sorts Lua seems like the only good option, we don't need everything from Python just to execute some functions in YimMenu or to expose natives.
Lua is nice because it doesn't provide all the other stuff that JavaScript (v8) or Python include out of the box.

I'll close this issue, for other people finding this issue please see #83.
