### ISSUE TITLE
[Request]: Update feature list

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1093]
### Solution

Maybe a list of things that are new to the menu on the release tab.

### Reason

Instead of going to commits and trying to find new things, this would make it a little more streamlined.

**Comment by ghost** [comment]
hardcode a number on the client, and upload a text file to dropbox with the same number. if the numbers dont match then update the local number to the server number and show the changelog. you can also have it read from a text file through dropbox to display the changelog information in game. this way the changelog can be edited if features were forgotten without having to push new commits.

or dont use dropbox idc same concept

**Comment by Seanghost117** [comment]
I'm sorry but this is very pointless, this is not a paid cheat, we are not going to sit here and provide a change log for every single commit that gets made especially with the amount that do get made. This is why we have PR templates, if people want to see change logs they have the ability to click the commit history and see details about the individual commits. Also the text file thing is such a pointless method, firstly we have a metadata json file and it isn't hard to increment a version number on each push to the master using a CI Job or something but again this is pointless. We aren't just going to keep updating a features list and have it pull from the GitHub because some people are generally too lazy to just click a link. They get the build from GitHub and it takes equally as many clicks to see commit history / details

**Comment by Yimura** [comment]
There's a sort of changelog available but it solely depends on people using the proper committing style written in the CONTRIBUTING.md file.

https://yim.gta.menu/changelog

Though I will not work on providing a self-written changelog.
