### ISSUE TITLE
[Request]: Nuke Vehicle

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1247]
### Solution

A car that when shot, create a nuclear explosion (see clip below)

### Reason

it is really cool and trolling would be insane.

### Additional context

https://user-images.githubusercontent.com/80224521/232324090-be24838e-d780-4c74-a273-df0424d96833.mp4

*this is from a stand plugin someone in online showed me*

**Comment by Rxann** [comment]
turn on volume to hear it. its kinda loud

**Comment by iswaxan** [comment]
shit is crazy hope it gets added

**Comment by Rxann** [comment]
I know, but how I or anyone could implement this is beyond me ( i am not the smartest though )

**Comment by iswaxan** [comment]
> I know, but how I or anyone could implement this is beyond me ( i am not the smartest though )

idk and might never know

**Comment by Tayipc38** [comment]
> I know, but how I or anyone could implement this is beyond me ( i am not the smartest though )

That is rather easy. Since spawned explosions are networked, only thing left to do is to write a little algorithm to modify a vector variable iteratively and spawn an explosion on each iteration. Or predefine all vectors and spawn the explosions simultaneously. As for the particle effects of the explosions, they can be supported with the networked PTFX natives of which the Orbital PTFX is rather large in itself.

**Comment by Rxann** [comment]
Alright, thanks for the explaination. Do you want to make this feature?

**Comment by Yimura** [comment]
Can be implemented through a Lua script.
