### ISSUE TITLE
[Bug]: Override local time makes the world flicker

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#1287]
### Describe the bug

When enabling Local time override (under World -> Time and Weather -> Local Time -> Override local time) it makes the world (ground) flicker.

### Steps To Reproduce

1. Enable Local Time under World
2. Enable Override Time
3. Set the time to 12 hours or so for the best effect
4. For better effect get into a flying vehicle and fly around

### Expected Behavior

For the world to not flicker

### Store

Rockstar

### Additional context

It might have something to do with graphics settings if you don't get the same effect as I did.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by maybegreat48** [comment]
Cannot reproduce. Can you record a video?

**Comment by sch-lda** [comment]
I have encountered the same problem in some missions.Yimmenu uses a looped command to overwrite time.It seems that the game itself tries to use a looped command to lock the time in some missions,too. This makes the light  cycle on and off quickly and leads to this issue.The same for the rendering of light effects in the game
I think this issue is difficult to solve unless the game itself is completely prevented from modifying the time

**Comment by Harmless05** [comment]
I cannot seem to reproduce it again. But when I did get it, I was on a mission.
This issue could perhaps be lessened by slowing down the time change rate.
I will try to get a video when I get the flicker again.

**Comment by Harmless05** [comment]
Yes, @sch-lda it only seems to happen in a mission.

https://user-images.githubusercontent.com/88204341/234306058-fee1216e-1ed0-424c-8c42-1010bf81a255.mp4

**Comment by Yimura** [comment]
We can maybe hook the natives used to set the time and prevent them from working when override time is set.
