### ISSUE TITLE
[Request]: Add disable/enable option for controller support in context menu

### ISSUE THREAD

**Issue by NRG0714** [Yimura/YimMenu#1289]
### Problem

It's kind of annoying to switch from keyboard to controller to fly helicopters/planes, and then suddenly having stuff for the context menu pop up when pressing A/X.

### Solution

Add an option in **Settings** > **Context Menu** options to disable/enable controller input/support for the context menu.

### Reason

I mostly find myself only ever using the context menu when using my keyboard, and I just switch back to it from the controller when I want to use it anyway.

### Additional context

N/A?????

**Comment by TheGreenBandit** [comment]
you can disable the context menu in the settings.

**Comment by NRG0714** [comment]
I know, I'm only asking for an option to disable/enable controller input for the context menu. Disabling the context menu every time I'm gonna pick up the controller is just annoying.

**Comment by binded-zz** [comment]
i play with controller too i ended up just disabling the display of the context menu because turning it off it turns back on with every restart
there needs to be some sorta better context menu control with controller its never the action that you expect it to be  triggers move back and forward but activate at the same time
