### ISSUE TITLE
Building fails: "Cannot use __try in functions that require object unwinding"

### ISSUE THREAD

**Issue by ThatKakiGuy** [Yimura/YimMenu#13]
When I try to build the projects it spits out this error message:
```
Error  C2712 Cannot use __try in functions that require object unwinding invoker.cpp 33
```

**Comment by Yimura** [comment]
You're trying to build the `Debug` version of YimMenu.
Probably would be best to just ignore debug build since its performance is really poor and you probably won't ever need the debug build, just use the release build.

Reference: 
- https://www.unknowncheats.me/forum/3323503-post96.html
- https://www.unknowncheats.me/forum/3323520-post97.html

**Comment by ThatKakiGuy** [comment]
Ah, thanks
