### ISSUE TITLE
Uuuh did you allowed Loko (Prometheus owner) to use your code ?

### ISSUE THREAD

**Issue by iswaxan** [Yimura/YimMenu#1348]
Here an image. ![image](https://github.com/YimMenu/YimMenu/assets/78171263/010d892d-1d66-4943-b731-87b44c5f9def)

**Comment by Rxann** [comment]
All major menus, including paid ones like Stand use Yim Protections

**Comment by iswaxan** [comment]
> All major menus, including paid ones like Stand use Yim Protections

Oooh k

**Comment by ghost** [comment]
YimMenu is open source. Anyone can use it as long as they follow the license yimura has created (which no one does unfortunately)

**Comment by Rxann** [comment]
Easy lawsuit... or legal action. Or even a nice payday due to the fact they made money off of the code they stole.

**Comment by Tayipc38** [comment]
> Easy lawsuit... or legal action. Or even a nice payday due to the fact they made money off of the code they stole.

Not exactly legal grounds when the project itself is a third party software wholeheartedly despised by a commercial product. It's like calling the cops because some dope head stole your meth. Although I do see the potential of making some money by exclusively leeching of this codebase, It does annoy me a little bit.

**Comment by xiaoxiao921** [comment]
> > Easy lawsuit... or legal action. Or even a nice payday due to the fact they made money off of the code they stole.
> 
> Not exactly legal grounds when the project itself is a third party software wholeheartedly despised by a commercial product. It's like calling the cops because some dope head stole your meth. Although I do see the potential of making some money by exclusively leeching of this codebase, It does annoy me a little bit.

Copyright rules still apply, not sure what the fuck you are saying, this project isn't getting dmcaed because there is nothing to DMCA, however yes those p2c are not respecting the license, which can have legal issues

**Comment by Tayipc38** [comment]
> > > Easy lawsuit... or legal action. Or even a nice payday due to the fact they made money off of the code they stole.
> > 
> > 
> > Not exactly legal grounds when the project itself is a third party software wholeheartedly despised by a commercial product. It's like calling the cops because some dope head stole your meth. Although I do see the potential of making some money by exclusively leeching of this codebase, It does annoy me a little bit.
> 
> Copyright rules still apply, not sure what the fuck you are saying, this project isn't getting dmcaed because there is nothing to DMCA, however yes those p2c are not respecting the license, which can have legal issues

I might not know legislation and copyright rules, but I do know formal and non-condescending language gets us further.

**Comment by Rxann** [comment]
> > > Easy lawsuit... or legal action. Or even a nice payday due to the fact they made money off of the code they stole.
> 
> > 
> 
> > Not exactly legal grounds when the project itself is a third party software wholeheartedly despised by a commercial product. It's like calling the cops because some dope head stole your meth. Although I do see the potential of making some money by exclusively leeching of this codebase, It does annoy me a little bit.
> 
> 
> 
> Copyright rules still apply, not sure what the fuck you are saying, this project isn't getting dmcaed because there is nothing to DMCA, however yes those p2c are not respecting the license, which can have legal issues

I was talking about the menu's that are taking YimMenu code.

**Comment by gir489returns** [comment]
I used to capture paid GTA V hack DLLs in the wild. Going as far back as 2015 people have been stealing open source projects and just recompiling them and selling it. I caught a few using my fork of m0d-s0biet-v with my logging strings in it, posted it to UC (and even offered to crack the DLL) the next release the strings were taken out. Like magic. Then BigBaseV2 started getting popular, people pasted that, and then I released my vehicle saver on UC, people pasted that too, found a lot of DLLs contained the same code for it. It will never change, and filing a DMCA takedown against a cheat is stupid, do you really think someone who's violating Rockstar's DMCA rights is going to respect your DMCA rights?

**Comment by xiaoxiao921** [comment]
None of the code in this repo is owned by rockstar. It could be that you are thinking about the natives function definitions but the Oracle v. Google case set a precedent that only the implementation (the body) of methods could be protected.

**Comment by Yimura** [comment]
Honestly it's just best to ignore it, the license is there more as to make it clear that anyone can use it.
The open sourcing part when people use the source code is just more as a friendly reminder to share with the community what you're working on.

**Comment by Sainan** [comment]
> All major menus, including paid ones like Stand use Yim Protections

This is simply not true. Stand has many, many more protections, crash patches, and overflow patches than this menu — and we offer this for free.

Also, this whole thread is kind of hilarious. In a scene built around violating copyright (or at least the DMCA), you can't cry that your license is not being respected and everyone and their mom now uses your work however the fuck they please. This whole open-source menu thing was just such a hilariously bad idea and now you're just high on copium.

**Comment by Yimura** [comment]
> This is simply not true. Stand has many, many more protections, crash patches, and overflow patches than this menu — and we offer this for free.
> 
> Also, this whole thread is kind of hilarious. In a scene built around violating copyright (or at least the DMCA), you can't cry that your license is not being respected and everyone and their mom now uses your work however the fuck they please. This whole open-source menu thing was just such a hilariously bad idea and now you're just high on copium.

Oh hi there @Sainan, I hope you’re having a wonderful day.
I was hoping you could enlighten me on why this “whole open-source menu thing” is “such a hilariously bad idea”.
The code is obviously open-source and at the end of the day we all know that people will steal code and not respect the license.

Kind regards,
Yimura

**Comment by Sainan** [comment]
You really don't see the problems of allowing everyone to copy-paste whatever features they want then sell them as part of whatever menu they make, while you and your contributors don't make a single cent?

And let's not delude ourselves about this being such a great menu. No one actually uses YimMenu or forks of it, it's really bad because there is no competent maintainer, so it is only good for stealing individual features.

**Comment by ghost** [comment]
> You really don't see the problems of allowing everyone to copy-paste whatever features they want then sell them as part of whatever menu they make, while you and your contributors don't make a single cent?
> 
> And let's not delude ourselves about this being such a great menu. No one actually uses YimMenu or forks of it, it's really bad because there is no competent maintainer, so it is only good for stealing individual features.

I think you missed the whole idea of it being open sourced, this is a pretty good free menu as it offers a bunch of stuff for free, on paper it's a pretty good idea. The community can 'make' their own menu using this and your point of having 'no competent. maintainer' is simply not a fair point, most of the contributors do this as a 'hobby' and not everyone is 'as skilled as you', you should honestly go touch some fucking grass dude.

**Comment by Sainan** [comment]
I'm just saying that it's a fruitless effort that only exists to allow people to steal from it, which I think is a view grounded very much in the reality of what this project is.

**Comment by ghost** [comment]
> I'm just saying that it's a fruitless effort that only exists to allow people to steal from it, which I think is a view grounded very much in the reality of what this project is.

You do realize, people can almost instantly tell if someone stole this right? Take for example the no clip, my favourite test to see if a menu is pasted.

**Comment by Sainan** [comment]
You clearly don't get it.

**Comment by xiaoxiao921** [comment]
It's you who don't, none of the maintainers care if others copy-paste what's in this repo, if they did, we'd actively hunt them down or simply not contribute. You're so short-sighted that all you can think of is potential revenue wasted because we dared to consider this a hobby project that we enjoy. The only reason you posted there is because you're seething that someone told you're actively monitoring the repo (like every other p2c) looking for something to grab because none of you can be bothered to reverse-engineer or code something on your own lol.

**Comment by tupoy-ya** [comment]
> You do realize, people can almost instantly tell if someone stole this right? Take for example the no clip, my favourite test to see if a menu is pasted.

Not that many people even know YimMenu exists.

<hr>

> And let's not delude ourselves about this being such a great menu. No one actually uses YimMenu or forks of it, it's really bad because there is no competent maintainer, so it is only good for stealing individual features.

Well yes YimMenu is very unstable and pretty much unusable, most contributors don't even play GTA 5.
And that is the thing with YimMenu - most people who make it are not interested in playing GTA 5 and make this menu because they like to make this menu.

> You really don't see the problems of allowing everyone to copy-paste whatever features they want then sell them as part of whatever menu they make, while you and your contributors don't make a single cent?

Contributors contribute not because they are getting paid but because they like to change something in this menu.

I'm pretty sure every one contributing is completely aware that there is nothing stopping someone from stealing their code making it closed source and profiting off of it.

> This is simply not true. Stand has many, many more protections, crash patches, and overflow patches than this menu — and we offer this for free.

> This whole open-source menu thing was just such a hilariously bad idea and now you're just high on copium.

Not everyone is willing to use your "free" menu, some people are interested in an actually free menu.
So i'm interested to know how people who wanted a Free and Open Source menu will just go and use stand "free".

>  No one actually uses YimMenu or forks of it.

This is simply not true.
Source - trust me.

**Comment by Sainan** [comment]
> that someone told you're actively monitoring the repo

If I were actively monitoring, I would've responded far sooner than a month later. I was just linked this thread and felt the need to correct the misinformation.

---

> Not everyone is willing to use your "free" menu, some people are interested in an actually free menu.
> So i'm interested to know how people who wanted a Free and Open Source menu will just go and use stand "free".

It depends. If you want something that's good and actually works well, you use the big, commercial product, but if you really value "Free and Open Source" above functionality, then, sure, go with something severely sub-par, but don't be surprised it won't be all you hoped for.

On another note, open-sourcing the various patches that Stand makes to GTA V is definitely a big consideration for me, because I myself like open-source, but it has to be done right, and I don't think YimMenu is it. Anyway, ultimately, it would be a lot of effort to maintain separate projects for something that we'd have no real incentive to do. So, it's all in Stand because it's just easier, and you can't really argue with the value proposition of getting the best protections for free, even if not with source code included.

> No one actually uses YimMenu or forks of it.

Well, this may not be true per-se, but you yourself pointed out that YimMenu is very unstable and unusable, which is what I was alluding to with this.

**Comment by xiaoxiao921** [comment]
> If I were actively monitoring, I would've responded far sooner than a month later. I was just linked this thread and felt the need to correct the misinformation.

Every p2c has to monitor it in case someone contribute something they don't have (global remote writing for example) because otherwise the product will be deemed as inferior. The same thing as you should reverse every other p2cs available to see how they do certain stuff etc.

> On another note, open-sourcing the various patches that Stand makes to GTA V is definitely a big consideration for me, because I myself like open-source, but it has to be done right, and I don't think YimMenu is it.

> Anyway, ultimately, it would be a lot of effort to maintain separate projects for something that we'd have no real incentive to do.

Impressive, you manage to contradict yourself from one sentence to another lol.

On another note, i'm not so sure you should be so proud of Stand and present it as "something that's good and actually works well, you use the big, commercial product," when you got such an UI lol

**Comment by Yimura** [comment]
Would you have ever considered making those patches opensource if it wasn't for YimMenu making the first steps towards opensource? Sure the project is far from perfect and YimMenu has far outgrown what it initially was meant to be.

I'm happy with what we've achieved with this project and indirectly raised to bar of what should be expected of a free menu (and paid cheats). Sure we might not be very stable outside of freemode but honestly that's because velocity was prioritised over stability. In the end there isn't much that can be done. Most people are only interested in new features not in having a stable menu per se. I've recently tried to stop accepting feature PR's and instead look into fixing bugs however there was little interest and I'd have to invest mostly my own time into finding bugs, reproducing them and then try and fix them.

And for a couple of random people I still think we have done well in our reversal work, without having the source code of 1.54 or a pdb of GTA V. Never went out of our way to pay money to shady individuals to buy some protections... In the end the limit lies with my capabilities and I'm very grateful to everyone that helped to adding more protections to YimMenu.

As for money, the goal was never to make money from this project, I was about to quit GTA V modding/didn't want to bother working on my own private source code so I made it open source. Because of the interest shown by the community I decided to continue developing a bit more and here we are almost 2 years later with over 54 contributors, some with more notable contributions than others (all of them just as welcome).

**Comment by Sainan** [comment]
> Every p2c has to monitor it in case someone contribute something they don't have (global remote writing for example) because otherwise the product will be deemed as inferior. The same thing as you should reverse every other p2cs available to see how they do certain stuff etc.

I've never reverse-engineered another menu. All my REing efforts go towards GTA V, because that is what matters. I look down upon some of the folks in this scene (including YimMenu contributors) who are so pathetic they had to resort to REing Stand to get their features.

> when you got such an UI lol

You're clearly not arguing in good faith, or you just didn't manage to find the appearance settings in the menu.

---

> Would you have ever considered making those patches opensource if it wasn't for YimMenu making the first steps towards opensource? Sure the project is far from perfect and YimMenu has far outgrown what it initially was meant to be.

YimMenu is not a consideration in this. It's purely from a matter of "What is the effort required of me? What do I get in return for that effort?"

> And for a couple of random people I still thing we have done well in our reversal work, without having the source code of 1.54 or a pdb of GTA V. Never went out of our way to pay money to shady individuals to buy some protections... In the end the limit lies with my capabilities and I'm very grateful to everyone that helped to adding more protections to YimMenu.

Jesus christ, that's a lot of speculation in one paragraph. Sure, because I have skill and the brains to acquire money, I could in turn use that money to buy some helpful things, but you seem to think I bought a lot more things than I did.

On another note, the one time I bought code was really underwhelming. Sure, it allowed me to provide users with a feature quickly, but it was only months later when I actually went and did the effort I at first "paid to skip" that the feature was something I could be happy with.

> As for money, the goal was never to make money from this project

I understand that, but does it not bother you, that others profit off of the work you and your contributors put here?

**Comment by Yimura** [comment]
> Jesus christ, that's a lot of speculation in one paragraph. Sure, because I have skill and the brains to acquire money, I could in turn use that money to buy some helpful things, but you seem to think I bought a lot more things than I did.

I never mentioned or directed it to you, it was to p2c's in general, you could or couldn't have it, only you would know that.

> I understand that, but does it not bother you, that others profit off of the work you and your contributors put here?

I'd rather the whole community benefit from making things public for free without pay-walling them/having to make money from it. It's all to just spread knowledge of what can be done, I have seen many people that knew less than me jumped in to help with YimMenu and have now way surpassed me in knowledge of GTA V.

**Comment by Sainan** [comment]
Well, this is a scene that thrives off some knowledge being unknown.

I wonder how many features were not made public because we didn't want some retard to PR it into YimMenu just for every skid menu to then have it. :^)

**Comment by xiaoxiao921** [comment]
> I've never reverse-engineered another menu. All my REing efforts go towards GTA V, because that is what matters. I look down upon some of the folks in this scene (including YimMenu contributors) who are so pathetic they had to resort to REing Stand to get their features.
 
That just screams being insecure about yourself, just because people know how to reverse a dll other than GTA you are calling them pathetic? Haha you good? Such scene are ruthless, where any mean will be deemed correct. How can you be so clueless about that?
 
 
> You're clearly not arguing in good faith, or you just didn't manage to find the appearance settings in the menu.

First impressions is all that matters, I just closed the menu after a minute because the UI was ass, big commercial product btw.

> I understand that, but does it not bother you, that others profit off of the work you and your contributors put here?

Repeating myself but so lost in your life you don't even understand that contributors in there do this for fun in their free time when they feel like it, they couldn't care less about skids that can't land a job because all they know is copy pasting other people code.

**Comment by Sainan** [comment]
You're clearly arguing in bad faith, but to address the UI thing at least: I think it's alright. Sure, I know magenta's not everyone's taste, but changing the primary colour is quick and easy. Other parts of the default theme include the most amazing smooth scroll you have ever seen in a menu, and the unique background blur effect. Even if these things are not apparent at first glance, it just shows the technical strength that Stand has to offer, and what it feels like to use a menu so polished.

**Comment by BugisoftRSG** [comment]
Imagine arguing about a almost decade old game with de facto no anticheat. Blur effect wow im so impressed totally unique.... jk.  You will die alone without friends and family. Most likely you have abandoned them due to your ignorance.

**Comment by Sainan** [comment]
I'm a sociopath, so probably accurate estimation, but you seem to forget how much I will have achieved professionally, compared to someone like you. 🙂

**Comment by rockband1488** [comment]
> You're clearly arguing in bad faith, but to address the UI thing at least: I think it's alright. Sure, I know magenta's not everyone's taste, but changing the primary colour is quick and easy. Other parts of the default theme include the most amazing smooth scroll you have ever seen in a menu, and the unique background blur effect. Even if these things are not apparent at first glance, it just shows the technical strength that Stand has to offer, and what it feels like to use a menu so polished.

You rely on a merry band of children to make your menu even remotely usable with themes and LUA scripts (which is frankly laughable, considering how much fucking money you ask for for a D3D framework with a native invoker slapped on it). 

You lack a chunk of options which everybody needs, yet you just spend time on developing a C++ API that no one really needs (and crashes, of course, because this community needs more of those!).

It seems evident that you, as a developer, are lacking in creativity, technical skills and are frankly quite naive.

For the longest time your menu had no sort of protection or obfuscation applied to it, and it got cracked every update, yet you want people to trust that it hasn't been thoroughly reverse engineered and turned inside out by someone at Rockstar Games already?

Why are you surprised if every second cheat developer in this community reversed your DLL while you kept it wholly unprotected on purpose, endangering every single one of your users?

Weren't you supposed to hand over development to someone else anyway? Or did that whole soap opera just not fly so you decided to drop it? You think we'd forget you were just a pedophile? Why don't you crawl back in the hole you came from? 

Proof: https://skid.sh/

**Comment by BugisoftRSG** [comment]
> I'm a sociopath, so probably accurate estimation, but you seem to forget how much I will have achieved professionally, compared to someone like you. 🙂

Achieved professionally, by doing cheats? Congrats man you helped humanity surely...

**Comment by rockband1488** [comment]
> I'm a sociopath, so probably accurate estimation, but you seem to forget how much I will have achieved professionally, compared to someone like you. 🙂

Making video game cheats is now a "professional achievement"?

With the crimes you committed obtaining some of the information necessary to build some of your features which you just said you "stumbled upon"; everything will come crashing down soon enough.

**Comment by rockband1488** [comment]
As a testament to this guy's profound god complex, here's a full dump of all the strings he tried "hiding" inside his executable.

Dumped in about 20 minutes with an automated tool, because of course. That's what you pay for, someone just using an open source xorstr library.

Full string dump in JSON format that can be applied in IDA when reversing this guy's "menu": https://anonfiles.com/Z9U1R4v6ze/stand_string_dump_json_txt
Full menu dump: https://anonfiles.com/v3V5Rev9z3/Stand_102_1_dump_dll
