### ISSUE TITLE
[Bug]: Context Menu

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1419]
### Describe the bug

Causing an Exception in the console(cmd) while the Context menu is open or being used, The working of Context menu: Its working normally but drops exceptions.

### Steps To Reproduce

1. Inject Menu
2. Go to Any ped or Entity(I tried on a Ped)
3. Open Context Menu on that Entity
4. Check Cmd for Exception logs (in my case).

### Expected Behavior

No exceptions should be caught.

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11760313/cout.log)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
Does it ever close your game or freeze it?

**Comment by CypherMorgan** [comment]
Nope, just same exception on loop until i close context menu

**Comment by Primexz** [comment]
wasn't able to reproduce this on rockstar version.

**Comment by CypherMorgan** [comment]
Try to open Context menu near multiple entities (like a group of peds) which must be in different areas of your screen.

and yeah, it sometimes happens and sometimes it doesn't.. But produced this like multiple times till now(as i used Context menu a lot).


Edit: I spawned a Car(Car Model: Cypher) then used it for a bit got out of it open context menu while standing beside it and got the Exception produced.

**Comment by alyxme** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/11789418/cout.log)
Same as TS I got this bug almost everytime (since 1.67 release). It happens when selection box of context menu is aiming at distant entities and you move it between certain entities/peds/cars. This bug cause temporal freeze (about 15-20 sec) with leaving session by timeout but in next lobby never happen again and seems everything else works ok then.

**Comment by CypherMorgan** [comment]
For me It freeze for like 1 second and back to normal without any session timeouts, Maybe cuz of my Rig idk.
