### ISSUE TITLE
[Bug]: Can't co-load with Stand

### ISSUE THREAD

**Issue by Sainan** [Yimura/YimMenu#1447]
### Describe the bug

Co-loading YimMenu with Stand currently freezes the game due to a bug introduced in 0ff99ececc8e5335c3d9a4f4242a5e4836d5c741 that causes YimMenu to refuse to run a sysDependency the game relies on.

Stand hooks this dependency to patch an array out of bounds that might occur within it. However, this hook trips the janky heuristic introduced in the afforemention commit.

### Steps To Reproduce

1. Inject YimMenu & Stand

### Expected Behavior

Game keeps running

### Store

Other (please mention in "Additional context")

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Sainan** [comment]
We will fix this in the next Stand release by using a different way to redirect execution for this hook.

**Comment by Tayipc38** [comment]
I dont see why this should be an issue on this repo.

**Comment by xiaoxiao921** [comment]
Are you saying that a specific sys dependency should be kept active? this is confusing

**Comment by Sainan** [comment]
I'm saying the queue_dependency heuristic is flawed. For more reasons than what is mentioned here.

**Comment by maybegreat48** [comment]
> Are you saying that a specific sys dependency should be kept active? this is confusing

I assume that Stand's hook places a jump instruction on the start of a dependency callback causing it to not run and freeze the game

> I dont see why this should be an issue on this repo.

Agree, considering that this is getting fixed in Stand anyway

**Comment by Sainan** [comment]
Well, Stand using a different way to hook a function hides a symptom but does not cure the illness.

As stated on Matrix, `sizeof(sysDependency) == 0xA0`, so you're also reading out-of-bounds on this struct, so... yeah. 😬

**Comment by Sainan** [comment]
Closing this because Stand """fixed""" this and there's clearly no interest in a second-rate menu like this to do things in a non-heuristic way.

**Comment by Yimura** [comment]
Mmmm I've read all what you said in this issue thread and seem to have missed what better options you mentioned. If you're so displeased then kindly never come here if all you're going to do is complain and go into arguments each time.

**Comment by Sainan** [comment]
See yesterday's Matrix discussion.

**Comment by Yimura** [comment]
Sorry but I don't use Matrix as an issue tracker, if you'd like us to reimplement the current way our queue dependency hook is setup.

You can make an issue, stating the problem, giving a solution and if need be give extra information.
Or you know directly contribute in a PR explaining what you've done exactly to fix the issue.

**Comment by Sainan** [comment]
In what world is the point of an issue tracker for the reporter to come up with and potentially even implement a solution?

I just pointed out the 0xE9 heuristic can go seriously bad. Clearly there was no interest here for it to be fixed, so I'm withdrawing it. Whatever.

**Comment by xiaoxiao921** [comment]
The heuristic doesn't go bad, it's not because your mod menu is conflicting with us that you should be that fucking annoying and spamming bullshit in there. imagine having the balls to say this when you are actually clueless about how the ac work, btw if anyone is not aware that dumbass paid thousands of dollars for knowledge about the ac and still have no idea how it work lmao

**Comment by Yimura** [comment]
Solutions are not expected to be given by a reporter necessarily, I don't expect everyone to exactly know how to resolve an issue.

I was just expecting you to know the solution to the problem you're referring to. Since the topic of this issue was originally phrased in a way that made it seem like you could solve it from your side I didn't bother investing more time into it.
If it's our problem you should make that clear in some way or another and if you're aware of a solution share it with us obviously (through the appropriate channels so we can keep track of it).

**Comment by Sainan** [comment]
As stated, Stand is only hooking a dependency to patch a logic error in it, so my knowledge is that 0xE9 does not mean it's a bad entrypoint.

Of course, I could fix this by using a different way to redirect execution that does not start with 0xE9.

Also, just because I don't know about your (public) methods of defeating the AC specifically, does not mean I don't know anything about it — I just prefer the kind of methods that don't get patched in the next update because they were publicly released on Github. 🤪

**Comment by xiaoxiao921** [comment]
Who asked

**Comment by Sainan** [comment]
You asked, indirectly.

PS: It would be nice if you could keep this irrational stuff in your pants whenever you see me.

**Comment by xiaoxiao921** [comment]
stop posting garbage in there, like I said no one care that an incomplete bypass of yours isn't working

**Comment by Sainan** [comment]
What are you even saying at this point?

**Comment by xiaoxiao921** [comment]
You think I'm gonna help you bypassing for free ? I can give you my PayPal if you want, I've heard you like buying that stuff since you are too stupid to figure that yourself

**Comment by Sainan** [comment]
I am not asking for an AC bypass?!

**Comment by xiaoxiao921** [comment]
What's up with having the reading ability of a 4-year-old and be proud of it?

**Comment by Sainan** [comment]
You're the one who's seemingly talking to himself...

**Comment by xiaoxiao921** [comment]
How does it feel exactly Sainan to have paid thousand of dollars for a bypass that is incomplete?

**Comment by Sainan** [comment]
If I paid 1000 dollars as you say I have, it feels like I easily make more than that in a day. 🙂

**Comment by xiaoxiao921** [comment]
Think about it for a second, isn't it rather revealing of how shitty a person life can become to spend thousands of dollars on something you're incapable of understanding yourself (i.e. because you're too stupid) and then think it's okay to brag about it on a public repo (the bypass is incomplete, don't forget) and think no one's going to call you out on it? Remember that no one asked about how stand hooks were doing, and you somehow thought we were gonna suck your balls because you are telling us that stand isn't coloading...

**Comment by Sainan** [comment]
You seem to completely forget the context of this issue report, so a hook Stand is making is very much relevant.

It's not even really related to AC, it's just basic "good code" VS "bad code", imo.

**Comment by xiaoxiao921** [comment]
The only bad code there is your shitty ass P2c not able to handle properly a single hook failing lol

**Comment by Sainan** [comment]
My hook succeeds. The problem is that maybegay's patch causes the hooked function to not get called anymore which in turn causes the game to hang as it waits for the dependency to finish running.

**Comment by xiaoxiao921** [comment]
You are seething, go touch some grass

**Comment by Sainan** [comment]
You are the one who is clearly having issues staying rational at the sight of my divinity.

**Comment by xiaoxiao921** [comment]
Have issue staying rational say Sainan who just called someone gay because Sainan code like a first semester student

**Comment by Sainan** [comment]
I always refer to him as maybegay.

Also, clearly my code standards are a lot higher than what can be observed on this repo, otherwise I'd not be here having to point out rather obvious issues.

**Comment by xiaoxiao921** [comment]
Why exactly are you talking about code standard when your menu is triggering a game hang because one of your hook is failing?

**Comment by Sainan** [comment]
🤦

**Comment by FIying-Scotsman** [comment]
I've got no skin in this argument but we've already had another issue closed because it became too heated - lets not repeat the same please. If you have to trade blows, please take it to Matrix or DMs (in Matrix).

Agree with @Yimura on this - the way it was phrased made it sound like you knew what was wrong and were withholding a fix. That may have not been your intention, but it reads like that. 

While you're not _expected_ to develop a fix, some info you did mention (like the 0xE9 patch causing it to hang) should have been put into the OP as a reason for fixing it with the caveat that _may_ be the reason for the issue but has not been confirmed. It's considered "dev manners" to provide all relevant info where you can in the initial ticket (even if it is edited in) after all even if it's unconfirmed/a theory (which is relevant regardless).

**Comment by xiaoxiao921** [comment]
The only reason tim came here is to complain that a ton of stand users keep saying they can't load it with Yimmenu and that he thought we cared about that for some reason. If he really cared about the community as a whole, he would have already fixed the problem with a contributor on matrix instead of crying like a kid in here. His intention was never to share anything, if you thought otherwise you are deeply mistaken

**Comment by Sainan** [comment]
I have provided all the relevant information in the issue. But I agree, if you need to be spoonfeed every little detail, then maybe 0xE9 is not obvious by just reading my issue and the problematic code alone. 🙃

**Comment by xiaoxiao921** [comment]
I think you forgot the part where you didn't even find this yourself in the first place
