### ISSUE TITLE
how lua script works on yimmenu?

### ISSUE THREAD

**Issue by TTV-Vicho** [Yimura/YimMenu#1591]

**Comment by Tayipc38** [comment]
You check the docs on the main page, make a script in lua and put it in your %appdata% yimmmenu scripts folder and it will load it automatically (or you can reload it manually).

**Comment by RainerZufall187** [comment]
everything is open source.

look it up yourself

**Comment by ghost** [comment]
it is surprising that the documentation for each lua for each menu is different and the scripts do not work accordingly in other menus. Which scripts from which menu can be compatible with the yimmenu? Or does each menu have its own lua?

**Comment by xiaoxiao921** [comment]
This is not at all surprising, every menu apis are coded by different people and even if there are similarities, developers usually end up with a different implementation and/or naming of the api for a multitude of reasons, ranging from personal preference to outright disagreement on how the api should be defined. I've been considering myself introducing some sort of converter / compat layer for kiddions scripts but unsure if i'll do it, because kiddion on his side might change the api down the line and I don't really want to keep chasing any change he might do just to make sure the compat layer stay updated and working

**Comment by Yimura** [comment]
And sure natives may be the same, but other functions that are exposed may not exist at all or be implemented dofferently internally.

**Comment by Yimura** [comment]
This should've been a discussion as this is not an issue with the code base.
