### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by lyxuo** [Yimura/YimMenu#16]
Suggestion
Hotkeys support for options
Simple crash protection, maybe blocking Invalid models(you could hook sync_can_apply)
Simple attachment protection
Add a Player history list

**Comment by Yimura** [comment]
Seems good will look into them, I have looked into adding hotkey support before and would definitely love for this to become a thing.

Attachment protection has been temporarily removed because it caused some severe problems in certain scenarios, I will be adding this back in a button you can press if someone has attached something to you, you can remove it.

Invalid model crash sounds good for me to implement, I'll be looking into it.

I don't like adding a player history list because it promotes toxic behaviour, I would like to know your reasoning on why this should be a feature.

**Comment by lyxuo** [comment]
> Seems good will look into them, I have looked into adding hotkey support before and would definitely love for this to become a thing.
> 
> Attachment protection has been temporarily removed because it caused some severe problems in certain scenarios, I will be adding this back in a button you can press if someone has attached something to you, you can remove it.
> 
> Invalid model crash sounds good for me to implement, I'll be looking into it.
> 
> I don't like adding a player history list because it promotes toxic behaviour, I would like to know your reasoning on why this should be a feature.

Hey, thank you for the reply. The only reason I think player history should be a feature is because if you are playing a mission/heist with a random, you crash or any kind of discounting you will able to look into the player list and add him, so you could run mission/heist again with him. In the same time I understand this also could be a very toxic option.

**Comment by Yimura** [comment]
Sounds reasonable.

**Comment by Yimura** [comment]
Closing this issue in favour for a more detailed and dedicated issue for each of the stated points.

All of the ones mentioned have either been added or requested in other issues.
#248 
#449 
#481
