### ISSUE TITLE
Mobile LS Customs (Vehicle Editor while not at LS Customs)

### ISSUE THREAD

**Issue by Slanderrr** [Yimura/YimMenu#173]
**Is your feature request related to a problem? Please describe.**
No, there is no problem. Just would love to edit the vehicle I am driving on-the-go.

**Describe the solution you'd like**
Essentially just asking for a submenu that will just allow for editing the vehicle.

**Provide Reasoning**
You guys are experienced developers and I am sure I am not the only one that would love this.

**Additional context**
N/A

**Comment by Slanderrr** [comment]
I forgot to mention, I know there is a button in the menu "Start LS Customs". However, that doesn't work unless you are in range of a LS Customs and the carmod_shop script is hooked. Otherwise, clicking that button will try start it, but exits immediately.

**Comment by Yimura** [comment]
Edit on the go, so you want to drive while changing the modkit of your car?

The current LS Customs is like this because it saves me the time to code out all the dynamic stuff and it's server-side, with this I mean that any changes you do to your own cars they'll be saved to Rockstar's servers.

I know the LS Customs might be janky from time to time but I distinctly remember that it used to work when near an LS Customs (when the script was already running), the script state probably got garbled which makes it then exit instantly, sometimes this can be fixed by driving outside the range of a LS Customs and back in.

Making a total custom LS Customs is not my priority and neither do I want a shitty PR adding this kind of stuff to YimMenu.

If someone where to attempt this, make a service for this, that stores all data for a car.
Use the natives for this that return the dynamic names for categories, mods, etc...
Also don't update this data each frame (which will be hard because Rockstar uses a static address to temporarily store such data, so you'll have to copy the string over to prevent it from changing).

**Comment by Slanderrr** [comment]
> 

So would it work on cars you just spawn in? Like cars that aren't even personal. But yeah, essentially just be able to edit whatever on the current vehicle the player is in.

**Comment by Vali0004** [comment]
> Edit on the go, so you want to drive while changing the modkit of your car?
> 
> The current LS Customs is like this because it saves me the time to code out all the dynamic stuff and it's server-side, with this I mean that any changes you do to your own cars they'll be saved to Rockstar's servers.
> 
> I know the LS Customs might be janky from time to time but I distinctly remember that it used to work when near an LS Customs (when the script was already running), the script state probably got garbled which makes it then exit instantly, sometimes this can be fixed by driving outside the range of a LS Customs and back in.
> 
> Making a total custom LS Customs is not my priority and neither do I want a shitty PR adding this kind of stuff to YimMenu.
> 
> If someone where to attempt this, make a service for this, that stores all data for a car. Use the natives for this that return the dynamic names for categories, mods, etc... Also don't update this data each frame (which will be hard because Rockstar uses a static address to temporarily store such data, so you'll have to copy the string over to prevent it from changing).

I already have something close in my personal menu, which dynamically parses all the data and stores them in arrays. The only issue is checking if they're in a new vehicle, and updating from there. As of right now, I'm able to store a vehicle once, clear it and then manually re-store data.
If I manage to find some system that's efficient and simple, I'll create a PR for it.

**Comment by dimmuboy** [comment]
I had a similar idea because in LCS is not possible to use all customizations on all cars

**Comment by mentolixite** [comment]
@GibsonHF's fork has the feature:

https://github.com/GibsonHF/YimMenu/blob/18651893a4b4de09344217d30d039e7925a3ae10/BigBaseV2/src/LSCTab.cpp
https://github.com/GibsonHF/YimMenu/blob/18651893a4b4de09344217d30d039e7925a3ae10/BigBaseV2/src/services/VehicleHelper.cpp
