### ISSUE TITLE
[Request]: Automatically kick out players in god mode

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#1738]
### Problem

I want the session to be free of cheating

### Solution

I don't know if there is a way to judge a player who is outdoors and has a mode of god and kick them out of the session

### Reason

1

**Comment by Yimura** [comment]
There's no way to detect accurately if someone is using godmode when they shouldn't. The game makes players god mode in certain legit cases and as such we can't just assume they're cheating if they have godmode.

We can only detect it when someone has godmode on and is attack another player at the same time, however I'm not sure this causes no false positives.

**Comment by iwanttodo1t** [comment]
Please allow automatic kicks to attack players using God Mode.

**Comment by Tayipc38** [comment]
> Please allow automatic kicks to attack players using God Mode.

I have adjusted the addinfraction function on my local to issue a kick upon that specific detection since those are mostly cheap or free menu users (hence the detection).

**Comment by rr1231234** [comment]
play on console if you want to play a no-cheat gtao

**Comment by gir489returns** [comment]
Not an argument, because there are hackers on the PS4 version, too.

**Comment by rr1231234** [comment]
> Not an argument, because there are hackers on the PS4 version, too.

i dont think so, modded accounts (cash, stats).. yes, head to r/gta5modding if you want

or OP could try fivem server too

**Comment by lonelybud** [comment]
what i can see now days is that there is a probabilty of certain modder launching session kick attacks (any kind) on you anytime they feel like and there is no chance of predicting that he/she will do that to you. And since they lauched the attack first before you there is a high chance you will be kicked out.

Also spoofing host token sometimes dont work if modders were already present before you (it seem like this way).

Now days in every other normal lobby (6/10) there is a network bail kick etc and lot of people are kicked. The host is too slow to react and players are kicked by that time.

**Comment by iwanttodo1t** [comment]
> > Please allow automatic kicks to attack players using God Mode.
> 
> I have adjusted the addinfraction function on my local to issue a kick upon that specific detection since those are mostly cheap or free menu users (hence the detection).

How to enable?

**Comment by RajaRam6** [comment]
> ### Problem
> I want the session to be free of cheating
> 
> ### Solution
> I don't know if there is a way to judge a player who is outdoors and has a mode of god and kick them out of the session
> 
> ### Reason
> 1
> 
> ### Additional context
> _No response_

[]()
