### ISSUE TITLE
[Bug]: Menu sometimes shows exception.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1825]
### Describe the bug

Sometimes the menu gives an exception during the game. I don't know why, I see that the menu throws an exception if I experience a momentary lag while playing.

### Steps To Reproduce

If you are lucky during the game it will appear to you.

### Expected Behavior

I don't know much, but I guess it shouldn't throw an exception.

### Logs and/or screenshots

[yimmenu.txt](https://github.com/YimMenu/YimMenu/files/12139966/yimmenu.txt)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
The exception handler in the menu catches everything from problems in the menu, crashes in the GTA5 process.
These crashes may include normal exceptions that may be caused by issues in the YimMenu code base or from looking at the exceptions in the partial log file you attached a crash in the GTA5.exe module.

These may be exceptions that slipped by our protections in YimMenu and will be caught by our exception handler as a last resort. You can usually ignore these as long as they don't keep occurring or freeze the game.

Do you know or remember what happened at the time the exception occurred? We can't make up a lot from these exceptions unless they have a clear step by step guide on how to replicate them. Obviously we could patch this single issue but that may not be the actual fix that's required to resolve the problem.

**Comment by grvelmaster** [comment]
It was an incident after my game lags in a version of the menu a few days ago. When I unloaded the menu, my lag problem was gone. When I felt lag, I knew there was an exception on the menu, but I had no idea what was causing it. Currently, I do not have this problem in the current version.

**Comment by ghost** [comment]
It was an incident after my game lags in a version of the menu a few days ago. When I unloaded the menu, my lag problem was gone. When I felt lag, I knew there was an exception on the menu, but I had no idea what was causing it. Currently, I do not have this problem in the current version.
