### ISSUE TITLE
[Bug]: uninject crash because of bad page protection

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#1828]
### Describe the bug

exception trace when uninjecting

https://github.com/YimMenu/YimMenu/commit/17d3ad7658173ecdae2449c2dfac67faf7fa6549#diff-00c985fbe069ff911f28289257791985e3ff67a618bbe929d229a7f36684b9a0R11-R15

### Steps To Reproduce

uninject

### Expected Behavior

don't throw exception inside memcpy

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
We need to either:
- check if the byte patch was applied first before restoring https://github.com/YimMenu/YimMenu/blob/17d3ad7658173ecdae2449c2dfac67faf7fa6549/src/memory/byte_patch.cpp#L7
- fix the only instance where this happen currently, which is here https://github.com/YimMenu/YimMenu/commit/17d3ad7658173ecdae2449c2dfac67faf7fa6549#diff-00c985fbe069ff911f28289257791985e3ff67a618bbe929d229a7f36684b9a0R11-R15

**Comment by gir489returns** [comment]
Should the commit be walked back while we fix this?

**Comment by Yimura** [comment]
@xiaoxiao921, this bug manifests differently. If the instance is successfully made then the restore should not cause a crash as the original bytes should have been copied.

The problem lies with the `m_window_hook` instance being invalid (?), I have no clue how this manifests though.
It then does a nullptr deref resulting in a crash.

However I do agree with some of the concerns you have, it's probably best to add some extra internal data to the byte_patch class to keep track of in which state the byte patch is.

**Comment by xiaoxiao921** [comment]
Found the real problem, which is described by this commit: https://github.com/YimMenu/YimMenu/pull/1831/commits/0053ef9a23f1e0f0507f102f9886f5c4606284ea

to be more specific, the memcpy access violation exception was triggered by https://github.com/YimMenu/YimMenu/blob/16e8e571f04b6d9d94f9be8c0d1823dc1088ae31/src/byte_patch_manager.cpp#L78

when that specific `byte_patch` was `restore`d
