### ISSUE TITLE
[Request]: detect who spawned squad to attack you.

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1880]
### Problem

Modders spawn squad to attack you without any reason.

### Solution

detect the player who spawned the squad

### Reason

annoy us and then kick us out if we say like "come out whoever is fucking around"

**Comment by ghost** [comment]
I think it would be much easier to make it so that the squads that they want to set on you will be teleported under the map or somewhere else so that they could not harm you.  I met this when I tried to spawn squads on a player, they appeared somewhere very far away and did not move, no matter where he was when they were spawned

**Comment by lonelybud** [comment]
good idea. this way we are not effected at all

**Comment by maybegreat48** [comment]
That's not possible. I guess we can add a toggle to prevent ped creation but that's basically it

> I met this when I tried to spawn squads on a player, they appeared somewhere very far away and did not move

Probably just a squad spawner bug
