### ISSUE TITLE
[Bug]: Using Clone PV plate will result in being kicked out of the vehicle

### ISSUE THREAD

**Issue by sch-lda** [Yimura/YimMenu#1936]
### Describe the bug

After selecting the Clone PV plate checkbox, spawning a cloned pv will result in the inability to enter the spawned vehicle. It is initially suspected that this line of code is causing the issue, but the specific reason is uncertain.

https://github.com/YimMenu/YimMenu/blob/e87931bf605cf967ac5b9d490bfa0dcb3c1bb168/src/views/vehicle/spawn/view_pv.cpp#L153C9-L153C9

### Steps To Reproduce

1.Inject
2.Use the settings as shown in the image
![image](https://github.com/YimMenu/YimMenu/assets/54973190/5c1da749-eb22-4563-b4b2-99c4d5abb043)
3.Click on a PV in the list
4.Be kicked out of the vehicle after a few seconds

### Expected Behavior

Will not be kicked out of the vehicle

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by spinoza-spinoza** [comment]
yes .it happened to me  .the vehicle appears then immediately disappears
the issue exist in 2 lastest  version 
i returned  to use  version august 1  there is no probleme

**Comment by Dennuz070** [comment]
How to get that version .. ?

**Comment by Dennuz070** [comment]
>  i returned to use version august 1 there is no problem. 
How to get that version .. ?

**Comment by Yimura** [comment]
Unable to reproduce, is this for other people or?

**Comment by sch-lda** [comment]
Screen record : ``` https://schplus-my.sharepoint.com/:v:/g/personal/admin_schplus_onmicrosoft_com/EWG6qmU5cTVJm7w4vgKZfuoBzQ5xOrm_TB-eb-Zn2usqvA?e=BY5ruN ```
Latest Release. Invite Only Session. Yimmenu folder has been cleared in advance.

**Comment by GTMoraes** [comment]
> Screen record : `https://schplus-my.sharepoint.com/:v:/g/personal/admin_schplus_onmicrosoft_com/EWG6qmU5cTVJm7w4vgKZfuoBzQ5xOrm_TB-eb-Zn2usqvA?e=BY5ruN` Latest Release. Invite Only Session. Yimmenu folder has been cleared in advance.

Curious. It seems that there are several exceptions thrown. Why so?
Have you tried with a different injector? I'm not sure whether that'd change anything, but mine usually never throws any exception, unless it's actually having issues.

**Comment by sch-lda** [comment]
> > Screen record : `https://schplus-my.sharepoint.com/:v:/g/personal/admin_schplus_onmicrosoft_com/EWG6qmU5cTVJm7w4vgKZfuoBzQ5xOrm_TB-eb-Zn2usqvA?e=BY5ruN` Latest Release. Invite Only Session. Yimmenu folder has been cleared in advance.
> 
> Curious. It seems that there are several exceptions thrown. Why so? Have you tried with a different injector? I'm not sure whether that'd change anything, but mine usually never throws any exception, unless it's actually having issues.

I think this is an accidental occurrence. I tested three different versions yesterday and no exceptions were thrown.

**Comment by GTMoraes** [comment]
I tried replicating this here, and also couldn't reproduce. I used the very same options visible from your video, and the car was spawned (with me inside) without any issues. I could drive, exit, enter it again etc.

**Comment by sch-lda** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/54973190/b2aaf85c-26dc-4d9a-b366-68e7d05a2dac)
I tried using Xenos64 injector again, but the problem still persists. Perhaps this is an issue related to the operating system environment or the game account?

**Comment by sch-lda** [comment]
Yesterday, I tried three versions: Nightly (commit e87931b), CI (commit 32472ff), CI (commit ee364cd). The first one had this issue, but the second and third versions work well. Based on commit ee364cd (built on my own computer), I repeated the test multiple times by adding and removing the line 'ENTITY::SET_ENTITY_AS_NO_LONGER_NEEDED(&veh);' in view_pv.cpp. I confirmed that the issue was caused by 'ENTITY::SET_ENTITY_AS_NO_LONGER_NEEDED(&veh); , but I cannot determine the exact reason.

**Comment by spinoza-spinoza** [comment]
the issu happed even in history mode

**Comment by spinoza-spinoza** [comment]
> the issu happed even in history mode

first  it say  to me you cant use this vehicle .i restarted the game    the  probeme persist   then i go to history the probleme  also  happen

**Comment by gir489returns** [comment]
I think I know why this is happening, and it's yet again another inconsistency between the Chinese version and the ROTW game. Chinese license plates are not allowed to contain certain words, things that reference stuff like the 1984 Tiananmen square massacre, Winnie the Pooh, Baozi, etc. There are additional checks on the vehicle done by Rockstar to see if these vehicles violate that, and I _**BELIEVE**_ it's done in the valentiner background scripts that are pulled down by your client when you first load it. I remember running into this issue way back when I was working on s0biet redux, a friend of mine was having a problem using the word Winning as his license plate, and it was just checking if the characters contained "WINNI" for the Chinese game.

While I don't see anything like that in your game per-say, it may have different/more stringent checks on spawned vehicles to combat cheating in Chinese clients, probably because cheating there is an actual crime, because the Chinese government owns 80% of all companies, and cheating on games like Genshin Impact directly hurt the government.

All that to say, I have no idea how to fix this for you without having a Chinese copy of the game to debug the issue.

**Comment by sch-lda** [comment]
A temporary solution has been implemented in Crazyzhang's Chinese localized version(Three Chinese users from different regions (Mainland China, Malaysia, Hong Kong) have reproduced the bug). If other users of the official version of Yimmenu encounter the same issue, remove "ENTITY::SET_ENTITY_AS_NO_LONGER_NEEDED(&veh);" introduced by commit e87931b and build to resolve this weird bug.

It's time to put an end to this stale issue
