### ISSUE TITLE
[Bug]: Opening the Hotkeys settings page causes the game to freeze

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#2113]
### Describe the bug

As reported by several people on UnknownCheats apparently there's a chance for the game to freeze after opening the Hotkey settings page.

### Steps To Reproduce

Open "Settings > Hotkeys" and get a the menu to freeze.

### Expected Behavior

To not freeze the game.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

https://www.unknowncheats.me/forum/3855623-post2062.html

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
And I guess not a single one of them posted their log.

**Comment by beepinboop** [comment]
The steps to reproduce are correct, open GTA in singleplayer mode (crashes on both online and singleplayer), inject it with Xenos, go to Settings > Hotkeys and the game crashes to desktop immediately.
Erasing %appdata%/YimMenu fixed the issue and I can't seem to reproduce it again, I've recovered the previous folder from the trash bin but I honestly don't remember which log(assuming it's one of the ones inside the /backup folder) has the issue I was facing, sorry.
Here's a catbox link with 11 logs from 09/06 to 09/11, I believe that the issue happened within these 5 days.
https://files.catbox.moe/rb5gif.zip

**Comment by Yimura** [comment]
@beepinboop could you instead include the settings file as well from your trashbin? That’s most likely causing the crashes.

**Comment by beepinboop** [comment]
Github doesn't accept .json files when uploading so I just changed it to a .txt.
[settings.txt](https://github.com/YimMenu/YimMenu/files/12600272/settings.txt)

**Comment by Yimura** [comment]
I loaded your settings.json and was unable to reproduce the bug.

**Comment by gir489returns** [comment]
This ticket sounds like yet another classic case of PEBKAC.

**Comment by beepinboop** [comment]
Not sure why you're being so aggressive when I've already mentioned that I've solved the issue by erasing the folder already.
I can't recall anything out of the ordinary that I've done in order to cause the crashes aside from setting up some settings and changing the hotkeys once (setting numpad1 to teleport to waypoint iirc). You can see the settings I've changed for yourself. Maybe the other guy who posted the same issue first in UC did something differently and may be able to help more.
I don't think that there's that many ways someone can screw up the menu in order to cause a crash.
I've managed to reproduce it two or three times **in a row** by simply booting up the game, loading the menu and clicking on "Hotkeys", the issue stopped after deleting the folder. That's all.

**Comment by Yimura** [comment]
Dated issue and nobody has since reported having issues with hotkeys.

**Comment by MARKa1230** [comment]
Hello, I have the same problem now. Can I find a solution
