### ISSUE TITLE
[Bug]: "No Recoil" stopped working

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#2120]
### Describe the bug

I turn on "No Recoil" and I still have recoil. This was not present a couple commits ago.

### Steps To Reproduce

1. Weapons -> No Recoil
2. Shoot, notice there is recoil

### Expected Behavior

There should be no recoil.

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
It's possible that the regression was made in this PR on the GTAV-Classes repo:
https://github.com/Yimura/GTAV-Classes/pull/136

**Comment by George0828Zhang** [comment]
@Yimura I have a theory: this is because the correct field should be `m_recoil_shake_amplitude` for this [line](https://github.com/YimMenu/YimMenu/blob/0c6acb758147b9d6eaddeaaafc268e9dfd69d12a/src/backend/looped/weapons/no_recoil.cpp#L34):
```cpp
weapon_mgr->m_weapon_info->m_explosion_shake_amplitude = 0.0f;
```
That PR changed the offset from
```
float m_recoil_shake_amplitude; //0x02F0
float m_explosion_shake_amplitude; //0x02F4
```
to the correct one
```
float m_recoil_shake_amplitude; //0x02F4
float m_explosion_shake_amplitude; //0x02F8
```
originally it is off by 4 bytes. With the correct offsets, the fieldname should be adjusted. I'll test and make a PR.
