### ISSUE TITLE
[Bug]: No recoil not working on snipers with scope

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#2133]
### Describe the bug

No Recoil works on every weapon but snipers with scope

### Steps To Reproduce

1. Turn on No Recoil
2. Shoot with any sniper with a scope

### Expected Behavior

Sights should not move (have no recoil)

### Store

Epic Games

### Additional context

No Recoil was very recently fixed but I guess this was missed out? I am pretty sure a couple commits ago, no recoil also worked on snipers, but I could be wrong.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Please provide the log file or this issue is useless.

**Comment by gamerboy1992** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/12618894/cout.log)
This?

**Comment by Yimura** [comment]
Unsure if you're aware but the current version of YimMenu is detected, so I'd suggest you don't use it unless you don't care about losing your account within the next 30 days.

Also I checked your commit hash and you're indeed using the version with the fixed offsets. [59cc4f2aa7b9617116a61c786f0a3d7493af0f12]

**Comment by gamerboy1992** [comment]
No, I was not aware. Thank you for the heads-up! Regardless, that is the only log file I could find and I am not sure if it is what it's needed.

I know the fixed offsets fixed the No Recoil for all weapons but these ones. Maybe it's what I said before and snipers with scopes never had a "No Recoil", but I just never noticed.

**Comment by Yimura** [comment]
Similarly older versions of YimMenu are also detected so you can use those either.

**Comment by gir489returns** [comment]
The sniper scope relies on a different field called punch_angles. I found them when I originally tried to make an aimbot for 323 just porting over my source engine cheat's aimbot to GTA V. If you look into the function that calculates the view for when you are scoped in, there's a check if the ped just fired, and it applies the punch_angles to the view's Y axis. You can either:

A: Zero out the punch_angles.
B: Cause the prerequisite check that it does to see if it's scoped in to fail via opcode replacement
C: Subtract the punch_angles from the view_angles when firing.

I did C when I wrote my aimbot, as that's what DarkStorm had to do anyway for TF2, since I always assumed every game had the same level of security the Source engine had. But A or B should work.

**Comment by gir489returns** [comment]
https://github.com/Yimura/GTAV-Classes/blob/3c7763fcf996f53f891e40f12bbfa8115fd612a7/weapon/CWeaponInfo.hpp#L350

I believe these are the punch_angles.

**Comment by George0828Zhang** [comment]
> https://github.com/Yimura/GTAV-Classes/blob/3c7763fcf996f53f891e40f12bbfa8115fd612a7/weapon/CWeaponInfo.hpp#L350
> 
> I believe these are the punch_angles.

These are for inverse kinematics, I've tested setting these to 0 but no effect.

This problem is related to weapon component: https://alexguirre.github.io/rage-parser-dumps/dump.html?game=gta5&build=2944&search=componen#CWeaponComponentScopeInfo
Apparently there's a `RecoilShakeAmplitude` field in `CWeaponComponentScopeInfo`, which should be inside `CWeaponComponentInfoBlob`'s `Infos` field.

Unless anyone knows the address or signature of `CWeaponComponentInfoBlob`, I can't verify it now.

Edit: or any offsets from CPedWeaponManager that relates to components.

**Comment by George0828Zhang** [comment]
~~I happen to stumble upon the scope amplitude offsets: https://github.com/GTA5TunersGenZ/GTA5TunersScript/blob/bf3a2c7f8a6c09b1d97749d426ae94670a08e698/GTA5TunersGenZ%20(v4.2p1.ct)%20(DLC%201.67).ct#L2261~~

EDIT: turns out simply zeroing the shake hash is sufficient: https://www.unknowncheats.me/forum/2152387-post2503.html
