### ISSUE TITLE
[Improvement]: persist vehicle - way to add vehicle to already existing folder

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2196]
### Which feature

currently i dont see a way to add vehicle to already existing folder. 
One has to manually retype the name of existing folder again to save a new vehicle.

solutions -

1. On dropdown menu change fill the save folder name (https://github.com/YimMenu/YimMenu/pull/2194)
2. Add a button or checkbox to prefill  save folder name from that of current selected folder name,
3. Rework entire UI.

### Reason

makes UX easy.

**Comment by gir489returns** [comment]
I think instead of populating the text box, because that's doing an action the user didn't ask for, if they have a drop-down already populated, we disable/remove the text box entirely. This would maintain consistency without how it worked prior, and only if the user has Root (Maybe we rename this to something the user can understand. Root implies they understand folder/structures and even how files are stored to disk. Maybe we call this something like None?)

This way, if they have the drop-down selected and start adding cars, it should only add cars to that drop-down, as they were already focused to that subfolder anyway. This would be a better UX IMO than some extraneous checkbox and populating a text box that they didn't ask for.

**Comment by lonelybud** [comment]
I agree with this.
