### ISSUE TITLE
[Improvement]: Tire Smoke Doesn't Save to JSON.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2239]
### Which feature

When saving a car with tire smoke it doesn't get saved in the json file. Both the tire smoke color and checkbox don't get saved.

### Reason

It'd be neat bc tire smoke is epic, not a priority or anything but I think tire smoke was just forgotten.

### Additional context

There's really not much else to say.

**Comment by lonelybud** [comment]
reproducible

**Comment by lonelybud** [comment]
smoke is actually saved as key `tire_smoke_color` but it is not added when car is spawned.

**Comment by ghost** [comment]
> smoke is actually saved as key `tire_smoke_color` but it is not added when car is spawned.

You right. 
I never checked the xml file until now tbh. So, it’s saved but just not being applied. Alright. Yeah, should be changed I think.

**Comment by lonelybud** [comment]
modify this current code from

https://github.com/YimMenu/YimMenu/blob/547fa1e137a501e76c019b5c20ea631ffa7a0a5e/src/services/vehicle/persist_car_service.cpp#L489-L498

to 
```c++
 if (i == MOD_TYRE_SMOKE) 
 { 
 	int tire_smoke_color[3]{}; 
 	VEHICLE::GET_VEHICLE_TYRE_SMOKE_COLOR(vehicle, &tire_smoke_color[0], &tire_smoke_color[1], &tire_smoke_color[2]); 
        vehicle_json[mod_names[i]] = "TOGGLE";    // this need to move here
 	vehicle_json[tire_smoke_color_key] = tire_smoke_color; 
 } 
```

this will make this code work and smoke will be applied

https://github.com/YimMenu/YimMenu/blob/547fa1e137a501e76c019b5c20ea631ffa7a0a5e/src/services/vehicle/persist_car_service.cpp#L254-L261

**Comment by gir489returns** [comment]
This got ported from my implementation of Persist Vehicle v5 or something like that posted to Unknown Cheats. The whole Vehicle JSON class should be redesigned to work with the intrusive helper instead of just using keywords as I didn't really understand how the nholman JSON class worked back then. Since it's my mess, I will clean it up.

**Comment by gir489returns** [comment]
To fix previously saved JSONs, just add the following line:

`"MOD_TIRESMOKE": "TOGGLE",`

You can place it anywhere, but the code will place it above MOD_TRANSMISSION because of alphabetical order. It does not need to maintain this to work, so long as it is inside the {} root brackets, it will work.

**Comment by lonelybud** [comment]
will the code be backward compatible to existing jsons?

**Comment by gir489returns** [comment]
> will the code be backward compatible to existing jsons?

The change is only in the persistence code that flushes it to disk.
