### ISSUE TITLE
[Improvement]: Animations' "List from Debug" be detachable/movable window

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#2283]
### Which feature

Animations > List From Debug window is not favorable in terms of checking animations variants. 

### Reason

In current state it obstructs the view of animation, having it as moveable like Debug tab is just QoL.

**Comment by gir489returns** [comment]
I seriously doubt someone from the team is gonna do something this stupid, if you want it done, you're probably gonna have to do it yourself on your own fork. Also, this breaks consistency with the project, as nothing besides the overlay is detached from ImGui left pane the menu generates, so I doubt it would be approved.

**Comment by binded-zz** [comment]
you might be interested in tupoyemenu 
there are tabs with movable windows 
his lite version is 3 weeks behind main 
i wouldnt use the master version as i dont know if it has the updates and is 3 months old 
although lua is sorta messed up because hes has tabs windows and not overlays i guess 
 
https://github.com/TupoyeMenu/TupoyeMenu
