### ISSUE TITLE
Add Pickup Kick Protection

### ISSUE THREAD

**Issue by Adler-D3R** [Yimura/YimMenu#229]
**Is your feature request related to a problem? Please describe.**
When I'm being Pickup Kicked (from tests with a friend), I crash.
Moreover, I'm using a protection that should block these pickup to spawn (using ReceivedEvent Hook).

**Describe the solution you'd like**
I'm not sure it's the best solution, but it should work : hooking CloneSync, and not syncing the pickup if it has this hash.

**Provide Reasoning**
It seems the menu is not protected against this kick, or maybe it is and it's coming from my code, since I've got a modified version of YimMenu. It's a kick which is really used by P2C, so if YimMenu is not protected against it, it will be a good thing it become protected against.

**Additional context**
No additional stuff to add.

**Comment by Tayipc38** [comment]
I have recently added the received_clone_sync to the menu. If you can make a clear statement of what should be blocked and when it should be blocked, I may be able to look into it and maybe even make a PR. I also suspect a different hook would be more suited to address this issue.

**Comment by Adler-D3R** [comment]
Hey Dayib, the hash used to Pick-up People is `vw_prop_vw_colle_alien`.
Blocking this pick-up will prevent to be kicked. It should be blocked before the player grabs it, so that the script does not crash because of the invalid location of the pick-up.

**Comment by Tayipc38** [comment]
> Hey Dayib, the hash used to Pick-up People is `vw_prop_vw_colle_alien`. Blocking this pick-up will prevent to be kicked. It should be blocked before the player grabs it, so that the script does not crash because of the invalid location of the pick-up.

I suspect this is one of many models that are malicious. If you could form a list of some sort and prove its malicious nature, Ill start working on a model blocker and include that list.

**Comment by SkiddyToast** [comment]
All figurine pickups have a check for the areas that they’re picked up in, if they’re not in the right area you get kicked, so you can check for any of the figurine models

**Comment by Adler-D3R** [comment]
Well yes, as Skiddy just said, that's all the pick-up model that give you RP like figurines.

**Comment by pelecanidae** [comment]
IIRC, the kick occurs because of the way `freemode` handles the pickup event. For example, look at `func_20206` (in 1.60); the second parameter is the pickup's "value" (the same field used for the amount of money when doing money drops). I don't have very good notes on this crash, but from reading my code, a protection is to ignore syncs of those particular pickups with values greater than 10 (?).

Other workarounds include patching the function directly in `freemode`, broadly [protecting against out-of-bound derefs in the RAGE VM](https://www.unknowncheats.me/forum/3075446-post22.html) (this is good to have anyway, because it's the basis for a bunch of other kicks), or hijacking the script event pool (e.g. hooking the first vtable func of `CEventGroupScriptNetwork`) and blocking any `CEventNetworkPlayerCollectedAmbientPickup`s with the relevant pickup models and suspicious values.

<details>
  <summary><code>CEventNetworkPlayerCollectedAmbientPickup</code> definition</summary>

Here's the latest `CEventNetworkPlayerCollectedAmbientPickup` definition I have for reference, it's probably from 1.0.2545.0:
```
struct CEventNetworkPlayerCollectedAmbientPickup {
  uint8_t pad_0[0x18]; // +0
  JOAAT pickup_model; // +18
  uint8_t pad_1c[4]; // +1c
  uint32_t value; // +20
  uint8_t pad_24[4]; // +24
  uint32_t sender_player_id; // +28
  uint8_t pad_2c[4]; // +2c
  JOAAT model; // +30
  uint8_t pad_34[4]; // +34
  uint32_t a7; // +38
  uint8_t pad_3c[4]; // +3c
  uint32_t a8; // +40
  uint8_t pad_44[4]; // +44
  uint32_t a9; // +48
  uint8_t pad_4c[4]; // +4c
  uint32_t a4; // +50
};
```

</details>

**Comment by SkiddyToast** [comment]
You can call the function at the 6th index of every `CEventNetworkWithData`, which copies 8 QWORDs of extra data to a pointer you specify, for this specific event, it copies everything from `pickup_model` to the end of your struct + 4

**Comment by SkiddyToast** [comment]
This is the struct I was talking about:
```
struct sAmbientPickupCollectedData
{
  _QWORD pickup_model;
  _QWORD value;
  _QWORD sender_id;
  _QWORD model;
  _QWORD unk_0x20;
  _QWORD unk_0x28;
  _QWORD unk_0x30;
  _QWORD unk_0x38;
};
```
This is what the 6th index function of CEventNetworkPlayerCollectedAmbientPickup looks like:
```
bool __fastcall GetCollectedAmbientPickupData(CEventNetworkPlayerCollectedAmbientPickup *this, sAmbientPickupCollectedData *data, int check)
{
  if ( !data || check != 64 )
    return 0;
  *data = *(sAmbientPickupCollectedData *)&this->pickup_model;
  return 1;
}
```

**Comment by Adler-D3R** [comment]
Actual Freemode patch solve this issue, we can close it.
