### ISSUE TITLE
Wanted Level

### ISSUE THREAD

**Issue by halny197** [Yimura/YimMenu#23]
Can you add something to stop the wanted level loop? The wanted level always changes to 0 even when I turned off the never wanted function.

**Comment by karifeld** [comment]
the problem is caused by [this line](https://github.com/iRevolutionDev/YimMenu/blob/4b0bc4d6d30374f96d0026291835bd79d7ca076c/BigBaseV2/src/backend/looped/self/police.cpp#L13), it seems that g.self.wanted_level is always prioritized.

you can revert to an older version [here](https://github.com/iRevolutionDev/YimMenu/blob/c508ed5faa052b23ea9a925b25c58211a38078da/BigBaseV2/src/backend/looped/self/police.cpp), but i dont think set wanted level function will work properly

**Comment by Yimura** [comment]
Yes, maybe just adding a second checkbox to force the wanted level, I would still allow the slider to work though if people want to set their wanted level once.

**Comment by ThatKakiGuy** [comment]
I just did some quick testing, commenting out the line 13+14 seems to fix it. I'm not sure why these lines are there in the first place.

**Comment by Yimura** [comment]
For the wanted level slider?

**Comment by ThatKakiGuy** [comment]
🤔 That one never worked for me. If I tried changing it I would always get a textbox with a 0 inside, and I couldn't write anything there.

**Comment by ThatKakiGuy** [comment]
Ok...
