### ISSUE TITLE
[Improvement]: Vehicle System

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2345]
### Which feature

PersistentClick with Shift to delete, as like in Teleports? I know how, but lot of user's have no idea what %appdata% folder is
Enter to last vehicle, teleport to last vehicle imho should be duplicated from Teleport to Vehicles Tab, Simple improvment.
When in car, button for cloning vehicle what you're in, or closest to You, just as simple as in Kidlons Menu by Modest
Kinda-rainbow-headlights? The same option as for rainbow paint, but for a headlights, probably easy to make that
Actually is it possible to change Deluxo top speed when flying? We can usehornboost, but not everyone knows

### Reason

GOODMODE update

**Comment by gir489returns** [comment]
I vote to reject this, as the teleport menu just uses one giant JSON file and it's not easy to work with JSON if you don't know what you're doing, but if the user makes a mistake and they misname a file, they can easily just remove it with Windows, I don't see why we should have to reduplicate Windows' job in the cheat.

**Comment by 7HA7MA77** [comment]
you closed my other bug report, where i reported 10 bugs, and you closed it because ONE of that errors were already reported. now you again do cherrypicking.. all of that just because i pointed your huge mistake you did? really, you felt so shamed after i pointed your huge error on other forum? there you were unable to delete my post, so people admited i am right, and here you hating every post i make, and you just abusing ur powers, sir? not nice. @Yimura, bro, can you please ask @girl489 about not acting like that, it's very unfair, and it's not good for project. I am making post to make YimMenu better, not to please gir489.

**Comment by V1RU513N** [comment]
szarpii back again 😴

**Comment by gir489returns** [comment]
> szarpii back again 😴

This is why children shouldn't be allowed to post here.

**Comment by Yimura** [comment]
@7HA7MA77, none of your previous issues or discussions on YimMenu have ever been deleted. If you visit the issues you posted in the past they’ll come back as 404 not found which may be because of your Github account being deleted in the past (in case you’re the @szarpii guy). If the issue/discussion gets deleted by the repository admin (me), it’ll come back as a “This issue has been deleted” making it very obvious on what happened.

Then onto your issue etiquette, you’re putting a bunch of requests into one issues. Now I ask you how you expect us to keep track on what we’ve implemented and what not? If we add one thing of this issue how do we cross that off our list? By closing the whole issue the way we usually do? No, not possible because there are multiple requests within this one issue. Then what? Look up this specific issue, edit the contents of the message to remove the request? Not everyone has access to editing the issues from other people so this is not a feasible option.

Kindly make issues the way they were intended to be made, any future issues with more than 1 topic in it will be closed.

**Comment by 7HA7MA77** [comment]
@Yimura bro, i can give You access to my accounts. After @gir made my 10 propositions hidden (after logout they invisible) i made 2nd account, as i thought okay, i see no point in arguing with a dummie, i just make new account, and make that propositions of improvement again, and it was okay for +/- 6hours, i checked it with my friend, he said yeah now they visible from his 2nd account, and after 6h they dissapered again. That account is 3rd. Maybe someone other made them hidden, idk, but gir have reasons to not like me, and maybe its him. I don't have any idea how, but i can give you access to my acocunts if you want to verify who did that, and who abusing powers to not let people talk, because they dont like them. 

Gir act childish, simply.. i am not posting here to make friends, and to gain his approvement, but to improve such amazing tool as YimMenu, share my ideas, and it shouldnt be like that, guy like gir should be able to abuse his powers, as that 'issues' tab on github is not a social media page, but a way of giving ticket to You, with propositions of ideas, or bug reporting. I do not want any opinions from guys like gir, or from other toxic persons, i just want to share my idea, and if You see them as no - okay, no. If You see them as worth to implement - amazing. That's all bro. I can share my passwords on discord if you want to verify how that happen, or i can post all my propositions there, as i have everything backuped... as it's not first case where overreacting staff member is too lazy to read whole message and deleting something because of that.. it's such a shame, but lot of companies have problems with bad people hired, i had that issue in my company too, where very valuable informations werent able to reach me as a ceo, because staff members were piece of.. piece of gir, hehe.. Also, sorry for not perfect english, i am not native speaker obviously. Peace!

**Comment by 7HA7MA77** [comment]
i almost forgot, nwk172 is my discord. @Yimura  :)

**Comment by 7HA7MA77** [comment]
//update
@gir489returns stolen that issue idea, and did it in such worse way
