### ISSUE TITLE
[Improvement]: Move or even better, duplicate button [GOODMODE]

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2351]
### Which feature

Enter to last vehicle, teleport to last vehicle button imho should be duplicated from Teleport to Vehicles Tab, as it's intuitive and it feels easier to access that way. I am not 100% sure if that's a improvement, so in that case would be great if other YimUsers would give a opinion, thanks! :)

### Reason

#GOODMODE update pack ^^

### Additional context

no needed

**Comment by gir489returns** [comment]
Nope.

**Comment by pierrelasse** [comment]
So you want a button that teleports / enters the last vehicle you where in?
If so you could easily make this into a script.

Also stop with this GOODMODE thing because it is distracting and weird and has nothing to do with the issue.

**Comment by gir489returns** [comment]
> So you want a button that teleports / enters the last vehicle you where in? If so you could easily make this into a script.

I actually had this in BBv2 because I would constantly jump out of helicopters or planes I was in by accident and ruin the mission. I feel it would be good contribution to the menu as a whole. It would be easy to implement, too as there is a native for it called GET_PLAYERS_LAST_VEHICLE.

> Also stop with this GOODMODE thing because it is distracting and weird and has nothing to do with the issue.

It's why I didn't even read the ticket and just closed it. But it seems that wasn't enough to stop his weapons grade autism.

**Comment by xiaoxiao921** [comment]
Trivially doable through a lua script
