### ISSUE TITLE
[Request]: Stream chat messages to "cmd window" [GOODMODE]

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2352]
### Problem

So, simple thing, even when i turn on Log Chat Messages, it's not visible in Yim's window, they only logged into appdata folder. @pierrelasse already made logging chat messages to YimMenu window in his amazing SussySPT LUA Script, and it works perfect, it should be implemented into native vanilla Menu i think, that's all :)

### Solution

@Pierrelasse

### Reason

#GOODMODE update pack ^^

### Additional context

no needed

**Comment by pierrelasse** [comment]
bro please stop.
and stop pinging me.
also this issue is already resolved.
and making new accounts and creating tickets over and over wont make them more intrested in doing your request.

**Comment by lonelybud** [comment]
i have already tried this in my custom build. Logging chat in console is wild. It mixes with other details.

**Comment by TheGreenBandit** [comment]
Please stop with this goodmode shirt

**Comment by 7HA7MA77** [comment]
> bro please stop. and stop pinging me. also this issue is already resolved. and making new accounts and creating tickets over and over wont make them more intrested in doing your request.

why people here so mean, you werent like that on discord. people are piece of shit on that github, fr. i made new accounts bcs one of crew member were deleting it. whatever. what i expected, lol.

**Comment by 7HA7MA77** [comment]
> Please stop with this goodmode shirt
you are piece of shirt. but okay, i stop. i should make my menu instead. you gonna heard about goodmode yet

**Comment by Yimura** [comment]
@7HA7MA77, you really think we can completely delete your issues out of existence right? Well we can't, remember that issue you renamed to "//delete". Well I deleted that an here is the link to that issue: 
https://github.com/YimMenu/YimMenu/issues/2349

See how it says "This issue has been deleted.", this means that we deleted it. Now let's take a look at one of the issues that you claim we deleted.
 - [The first one you made with your szarpii account](https://github.com/YimMenu/YimMenu/issues/2280)
 - [The first one you made with your nwk172 account](https://github.com/YimMenu/YimMenu/issues/2310)

Both of those return a page 404 not found error, meaning that they got completely wiped from existence.
Now this can either happen because Github staff deleted your issues or banned your Github account.
 - @szarpii
 - @nwk172

Both of those again return 404 not found, now you tell me what happened to those accounts? Perhaps you used some fake email service and got the accounts wiped after not verifying your email address or you did something else to anger Github staff.

Anyways stop blaming us for things we didn't do.

And as a final one, here is an issue that's a lot older than yours and Github doesn't remove/404 them if they get old enough:
https://github.com/YimMenu-Lua/submission/issues/1

**Comment by pierrelasse** [comment]
Damn a new detective was born 🕵️‍♂️

**Comment by gir489returns** [comment]
> Both of those again return 404 not found, now you tell me what happened to those accounts? Perhaps you used some fake email service and got the accounts wiped after not verifying your email address or you did something else to anger Github staff.

He probably annoyed them with that good mode shit and they couldn’t take it either.

**Comment by 7HA7MA77** [comment]
i added too many threads. i made multithread first, but you wanted me to split it. 
i had too much propositions, and github detected it as trying to flood system with advertising. 

@gir - we already know you cant read kid, but that propositions were to Yimura and other crew members who are inteligent and can read. propositions to make menu better. not to make you feel smarter. i know, i know.. you wont understand that reply too as its too long and too complicated for you. whatever.

**Comment by 7HA7MA77** [comment]
github staff member replied me that there is absolutely nothin wrong in them and said sorry but that how system works, and it's understandable. i was thinking that was the reason, but fact that gir took his voice made me think it was him. it was unneceasary, i should ignore that kid, stupidity is toxic, and he's perfect example of that. fk it. Sorry for blaming you guys, ima add one proposition daily, to not trigger antispam. Peace.

**Comment by gir489returns** [comment]
Seethe harder faggot.
