### ISSUE TITLE
Have you been banned? Ban data collection thread (2)

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#2425]
### Anyone coming here please provide the following information:

```
Date of ban:
YYYY/MM/DD

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
1 hour

Did you play any missions : 
Yes/No

Did you use any Lua's? : 
Yes/No

If yes, which Lua's did you use? : 

Did you ever cheat in any money? :
Yes/No

How much did you cheat in approx. and when:
1 million

Did you load any other menu's next to YimMenu? : 
...

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :


Are you tracking players using the player database? : 
Yes/No

Do you make use of the session browser? :
Yes/No


```

**Comment by lisarun** [comment]
Date of ban:
2023/12/15
How often do you play GTA V :
Daily
How many hours do you spend weekly on GTA V :
10 hour
Did you play any missions : 
Yes
Did you use any Lua's? : 
no
Did you ever cheat in any money? :
No
Did you load any other menu's next to YimMenu? : 
no
Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Version for October 12th
I only use YimMenu's function to prevent kicking, and to prohibit being kicked out

**Comment by lisarun** [comment]
Date of ban:
2023/12/15
How often do you play GTA V :
Daily
How many hours do you spend weekly on GTA V :
70 hour
Did you play any missions : 
Yes
Did you use any Lua's? : 
no
Did you ever cheat in any money? :
No
Did you load any other menu's next to YimMenu? : 
no
Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Version for October 12th
I only use YimMenu's function to prevent kicking, and to prohibit being kicked out

**Comment by akirayin** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Almost daily

How many hours do you spend weekly on GTA V :
ca. 20-30 hours but it depends

Did you play any missions : 
Yes

Did you use any Lua's? : 
Yes

If yes, which Lua's did you use? : 
casino pacino (podium vehicle 2 times normally, no cooldown wasn't used), sussy (testing it out in offline, didn't really use it for anything)

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:
0

Did you load any other menu's next to YimMenu? : 
No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Banned session didn't produce .log file, but the version used was current Nightly Build #761

Are you tracking players using the player database? : 
Yes (no action was taken using them and no new entries were added to it since the 1st suspension)

Do you make use of the session browser? :
Did in the past and got 30 days, NOT since the 1st suspension.

**Comment by sch-lda** [comment]
Date of ban:
2023/11/15

How often do you play GTA V :
occasionally (Just testing some things... in last 2 mo)

How many hours do you spend weekly on GTA V :
3~5 hours per week in last 2 mo

Did you play any missions : 
Only one heist preparation in last 1 mo

Did you use any Lua's? : 
Yes

If yes, which Lua's did you use? : 
always load: sch lua;  Just used for a very short time: Internet/SussySpt/Alicelua/Rscript

Did you ever cheat in any money? :
<1M in last 1 month

How much did you cheat in approx. and when:
<1 million in last 1 month, 500M in total

Did you load any other menu's next to YimMenu? : 
Kiddion (and lua)、stand (and lua)、cheatengine and several non-English menus  (May lose reference value because I used too many other tools in last 2 mo. lol)

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Always the latest version

**Comment by starwalker89** [comment]
Date of ban:
17/11/2023

How often do you play GTA V :
Diariamente

How many hours do you spend weekly on GTA V :
14 horas

Did you play any missions : 
Si

Did you use any Lua's? : 
No

If yes, which Lua's did you use? : 

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:


Did you load any other menu's next to YimMenu? : 
 No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
No lo sé, siempre lo use en su ultimas versiones

**Comment by rrAsus** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
1-2 hours

Did you play any missions : 
Yes

Did you use any Lua's? : 
Yes

If yes, which Lua's did you use? :
-auto-flip-vehicle
-set-veh-forward-speed
-set-veh-max-speed
-shift-drift

Did you ever cheat in any money? :
Yes

How much did you cheat in approx. and when:
6 million (Ceo Crate Method 3-5 Months ago)

Did you load any other menu's next to YimMenu? : 
No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
3275459431965e29905a8c2c77be220580a4894a

Are you tracking players using the player database? : 
Yes

Do you make use of the session browser? :
No

**Comment by MrJunius** [comment]
How often do you play GTA V :
occasionally

How many hours do you spend weekly on GTA V :
1-3 hours per week in last 3 mo Mainly Thursday

Did you play any missions :
Only 3 heist preparation in last 1 mo

Did you use any Lua's? :
Yes

If yes, which Lua's did you use? :
always load: Alicelua

Did you ever cheat in any money? :
yes

How much did you cheat in approx. and when:

<2 million in last 3 month,half year<40M in total
never modify dividends

Did you load any other menu's next to YimMenu? :
just yimMenu

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Always the latest version

**Comment by janka23** [comment]
Date of suspension:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
1 hour

Did you play any missions : 
Yes

Did you use any Lua's? : 
No

Did you ever cheat in any money? :
No

Did you load any other menu's next to YimMenu? : 
Loaded kiddions on accident once, dont think that affected anything.

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Downloaded it on october 30th, so whatever version it corresponds to that. Used solely for protection.

**Comment by NjuuOwO** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Nearly daily

How many hours do you spend weekly on GTA V :
10 - 25* hours

Did you play any missions : 
Yes

Did you use any Lua's? : 
Yes

If yes, which Lua's did you use? : 
Pessi, Ultimate, SussySPT

Did you ever cheat in any money? :
Yes

How much did you cheat in approx. and when:
500 millions, 1.5 month ago using Pessi Limited and Looped Transactions 

Did you load any other menu's next to YimMenu? : 
Kiddions

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
cadb6dab92a77210b04390d32c967be1f307a88a

**Comment by W1ldAustin** [comment]
Date of ban:
2023/11/15

How often do you play GTA V :
1-10 times a week (depends on how much time I have)

How many hours do you spend weekly on GTA V :
between 1-5 hours a week

Did you play any missions : 
no

Did you use any Lua's? : 
yes but not using Yim

If yes, which Lua's did you use? : 
Slient Night
Did you ever cheat in any money? :
yes (not using Yim)

How much did you cheat in approx. and when:
20 billion

Did you load any other menu's next to YimMenu? : 
Moddest

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Not seeing any logs but it was the latest

Is your player.json file empty? : not finding the json

**Comment by MBanka0436** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
When as (last run before lock 12.11)

How many hours do you spend weekly on GTA V :
3-6

Did you play any missions : 
Yes

Did you use any Lua's? : 
No

If yes, which Lua's did you use? : 

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:
\-

Did you load any other menu's next to YimMenu? : 
\-

Which commit hash is your version of YimMenu.dll (grab it from the latest count.log)? :
cadb6dab92a77210b04390d32c967be1f307a88a 
(I hope this is what you need) 

Is your player.json file empty? : No

Do you make use of the session browser? :
Yes

**Comment by Shenmuee** [comment]
Date of suspension:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
15 hours

Did you play any missions :
Yes

Did you use any Lua's? :
Casino sussy, set-veh-forward-speed,set-veh-max-speed, shift-drift a random event 

Did you ever cheat in any money? :
yes with kiddions

Did you load any other menu's next to YimMenu? :
kiddions , mini garage, lscHax

How much did you cheat in approx. and when:
100 million in a month with kiddions

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Always last release

**Comment by hl2jeep** [comment]
Date of ban:
Not banned yet, but i'm submitting this incase i do get banned, as i have been affected by the previous ban wave. I will update on if i get banned or not.

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
couldn't say, maybe about 10-20 hours?

Did you play any missions : 
Yes

Did you use any Lua's? : 
Yes

If yes, which Lua's did you use? : 
Harmless's LUA scripts: https://github.com/Harmless05/harmless-lua

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:

Did you load any other menu's next to YimMenu? : 
Used kiddions once before, but haven't used it since my last ban

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
3914ebee7285477a47f025ecde0223ebb2b4cd26


Is your player.json file empty? : No.

**Comment by hackerftsg** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
20 hour

Did you play any missions : 
No

Did you use any Lua's? : 
No

If yes, which Lua's did you use? : 

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:


Did you load any other menu's next to YimMenu? : 
No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
ba5610af99da7e450d497ad7c9decdad57880fad-dirty

Is your player.json file empty? :
No

**Comment by idontdef** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
20

Did you play any missions : 
Yes

Did you use any Lua's? : 
Yes
If yes, which Lua's did you use? : 
YimCeo
Did you ever cheat in any money? :
Yes

How much did you cheat in approx. and when:
20 million

Did you load any other menu's next to YimMenu? : 
No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :


Is your player.json file empty? :

**Comment by staysaucy** [comment]
Date of suspension:
2023/11/17 - 30 days

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
20 hours

Did you play any missions : 
Yes

Did you use any Lua's? : 
No

Did you ever cheat in any money? :
Yes, via paid services. Done over half a year ago before use of YimMenu.

How much did you cheat in approx. and when:
~$300 million

Did you load any other menu's next to YimMenu? : 
No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
0de9182735fd952febe5fb9bd9f447502df64764

Are you tracking players using the player database? : 
No

Do you make use of the session browser? :
No

**Comment by samueleul** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
3 hour

Did you play any missions : 
No

Did you use any Lua's? : 
Yes

If yes, which Lua's did you use? : 
Pessi v0.2 and Ultimate Menu V1

Did you ever cheat in any money? :
Yes

How much did you cheat in approx. and when:
50 million, i think 1 week ago

Did you load any other menu's next to YimMenu? : 
Kiddions

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
af287d259328c55b7a2d689fe2013d1521d62efe

Are you tracking players using the player database? : 
No

Do you make use of the session browser? :
Yes

**Comment by AcaroMan** [comment]
Date of ban:
2023/11/21

How often do you play GTA V :
Weekly

How many hours do you spend weekly on GTA V :
10h-20h

Did you play any missions : 
Online Jobs

Did you use any Lua's? : 
No

If yes, which Lua's did you use? : 
N/A

Did you ever cheat in any money? :
Yes, but using Cheat Engine

How much did you cheat in approx. and when:
In  total about 100M and at least 5 months ago

Did you load any other menu's next to YimMenu? : 
No

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
[d6c32533](https://github.com/YimMenu/YimMenu/commit/d6c32533be18aef5b35122b4f068b8844155751c)
Are you tracking players using the player database? : 
Yes

Do you make use of the session browser? :
Yes

**Comment by porccana** [comment]
Date of ban:
2023/11/17

How often do you play GTA V :
Daily

How many hours do you spend weekly on GTA V :
5-7 hours
Did you play any missions : 
Yes, Acid lab ones.

Did you use any Lua's? : 
Yes.

If yes, which Lua's did you use? :
SCH

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:
-

Did you load any other menu's next to YimMenu? : 
Cherax

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
7d3e75f260514a0b57d7150b4d6169f2869a6335

Are you tracking players using the player database? : 
Yes, ~5 or so tracked and over 1k in database.

Do you make use of the session browser? :
Yes. Used the feature to replace ig matchmaking.

**Comment by ipic01** [comment]
**I'm from China and I'm using a translator. I'm sorry if you can't understand.

Date of ban:
2023/11/21 ( Forever Banned )

How often do you play GTA V :
Two hours each morning and afternoon

How many hours do you spend weekly on GTA V :
30 hour

Did you play any missions : 
No

Did you use any Lua's? : 
No

If yes, which Lua's did you use? : 
None

Did you ever cheat in any money? :
No

How much did you cheat in approx. and when:
None

Did you load any other menu's next to YimMenu? : 
X0 Cheat（ Enable only disable idle shots ）

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
Latest

Are you tracking players using the player database? : 
I've almost never entered the public map so I don't know.

Do you make use of the session browser? :
No

**Comment by pzy2000** [comment]
Date of ban:
2023/12/20 ( Forever Banned )

How often do you play GTA V :
It depends

How many hours do you spend weekly on GTA V :
about 10 hrs the week before ban

Did you play any missions : 
Yes

Did you use any Lua's? : 
Yes, AND I DO THINK this is where the problem lies.

If yes, which Lua's did you use? : 

Alice lua(to win the grand prize car on the casino roulette wheel.)

Did you ever cheat in any money? :
No(I skipped prep mission 1 year ago, but I dont think its the cause)

How much did you cheat in approx. and when:
None in a year.

Did you load any other menu's next to YimMenu? : 
Kiddions(about 2 weeks ago)

Which commit hash is your version of YimMenu.dll (grab it from the latest cout.log)? :
603c3becb16bbb02d46e16d7fb756787428aaca6

Are you tracking players using the player database? : 
Yes

Do you make use of the session browser? :
Yes
