### ISSUE TITLE
[Bug]: Vehichlie [NoCollision] included character settings

### ISSUE THREAD

**Issue by Sheeeeit** [Yimura/YimMenu#2476]
### Describe the bug

Enable checkbox "No collision" in Vehichle tab and character will fall undermap when walking trough wall

### Steps To Reproduce

1. Open game
2. Inject DLL
3. Enable "No collision" for vehichle
4. Walk trough the wall
5. Will fall under map

### Expected Behavior

No collision "Self" and "Vehichle" for each one

### Logs and/or screenshots

[Video](https://mega.nz/file/IY9BiCyC#GdJIjtOwjymSuy5Vco_KjWLrZoGAlHUJJc0hzHsrc1g)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Can you disable no collision, no clip to the same spot you had this and then disable noclip?

See how you're falling through the map even with no collision disabled? This is because of the map just not having any collision under those buildings.
Because of this there's no way for us to fix this, can't fix a problem if there's no solution...
