### ISSUE TITLE
[Build]: I got problems while cmaking

### ISSUE THREAD

**Issue by sniperrich** [Yimura/YimMenu#2481]
### Describe the build issues

i use visual studio to cmake files
but i got problems
i followed the guide
<img width="1279" alt="image" src="https://github.com/YimMenu/YimMenu/assets/110087661/3e8d06b5-768b-44b9-9cdb-831309d0fb01">

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by lonelybud** [comment]
try this first https://code.visualstudio.com/docs/cpp/config-msvc if you are using vscode.
Otherwise visual studio works just fine.

After you able to compile your simple program. Then head over to https://github.com/YimMenu/YimMenu/wiki/Setup-your-PC-for-YimMenu-Development#making-changes-to-the-source-code

**Comment by Yimura** [comment]
Have you followed the setup guide properly? Have you search for the problem on Google first before coming here?
It seems to me that the error code is unrelated to YimMenu and a problem with your compiler installation being broken / not present.

This is the first link I got while searching for the issue on Google:
https://stackoverflow.com/questions/30553318/cmake-cl-exe-is-not-able-to-compile-a-simple-test-program

**Comment by sniperrich** [comment]
i found i didn't have system envionment variables
thks
