### ISSUE TITLE
Feature Suggestion: Expand teleport tab functionality

### ISSUE THREAD

**Issue by ThatKakiGuy** [Yimura/YimMenu#25]
- A way to teleport to the objective would be helpful for grinding out Special Cargo + Vehicle Warehouse
- Custom teleport locations for collecting all 200 Action figures and the collectibles in singleplayer

**Comment by Yimura** [comment]
The teleport functions I wrote can be used to teleport to blips.
Function in question:
https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/util/teleport.hpp#L101
List of blips:
https://docs.fivem.net/docs/game-references/blips/

Or you can just use the get blip location function and teleport to the coordinates returned.
https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/util/blip.hpp#L8

Probably would be best to use the blip location feature and then teleport to those coordinates, since the teleport to blip function overwrites the Z coordinate, regardless of if the Z coordinate is already included in the Vector3.

**Comment by ThatKakiGuy** [comment]
Ok, thanks, that should be easy to implement 😄

**Comment by ThatKakiGuy** [comment]
I tried `BlipIcons::Circle`, but it teleportet me right in front of a player, passing `HUD_COLOUR_YELLOW` to `to_blip` made it do nothing at all..

**Comment by Yimura** [comment]
That's why I haven't gone around to creating this feature, there are so many different blips, that look the same but have a different ID. There are even colors that are the same but have a different ID.
Could be that only one combination is used or it can be that the game uses multiple different blip ID's depending on the mission. What you can do is look into the decompiled scripts and see what blip ID's are used there.

![image](https://user-images.githubusercontent.com/24669514/147574435-7338b8f1-d374-42a6-bbe2-04c0ecc72922.png)
![image](https://user-images.githubusercontent.com/24669514/147574495-3b4ce392-683c-408e-85ee-b54a6507ce77.png)

**Comment by ThatKakiGuy** [comment]
Ok, thanks. How do I find and decompile the scripts? Are they somewhere in the .rpf files?

**Comment by Yimura** [comment]
https://github.com/Sainan/GTA-V-Decompiled-Scripts

**Comment by ThatKakiGuy** [comment]
Ah thanks 😄 Now I just need to find the right ones

**Comment by Yimura** [comment]
What also might help is looking through the scripts based on BLIP related natives, take for example the `HUD::ADD_BLIP_FOR_COORD` native. You can then follow the blip handle further down to where it's modified with `HUD::SET_BLIP_SPRITE`, to get the sprite that's used and optionally `HUD::SET_BLIP_COLOUR`.

You'll probably something that looks like:
```cpp
int blip_handle = HUD::ADD_BLIP_FOR_COORD(x, y, z);
// the order of the calls to these natives might be different
HUD::SET_BLIP_SPRITE(blip_handle, sprite_id); // sprite_id might be a hardcoded ID
HUD::SET_BLIP_COLOUR(blip_handle, colour_id); // colour_id might be a hardcoded ID
```

**Comment by ThatKakiGuy** [comment]
Yeah, I'm trying that but it's a pain to find the right one, I'm finding VIP blips, Package Blips, everything but not what I need 😅

**Comment by ThatKakiGuy** [comment]
Maybe I'm just looking in the wrong scripts, but I find the same ones every time, but no yellow dot 😆

**Comment by ThatKakiGuy** [comment]
Is it possible to log the sprite id when a new blip is created? Something like that would make this a whole lot easier..

**Comment by Yimura** [comment]
You can hook the native probably but I'm not on Windows right now, neither do I have a dump of the game available to create a signature of the native.

If you don't know how, take a look at the Dump entrypoints button, it's in the Debug Window, with that you can dump where the subroutines are for each native. Then with an IDA dump you can calculate the address at which the subroutine is located and create a signature of that. Afterwards you do the usual hooking as you'd do normally.

Otherwise search on the UnknownCheats forums for an explanation of what dump entrypoints does, how you create an IDA dump of the game, etc...

**Comment by ThatKakiGuy** [comment]
Ok thanks

**Comment by ThatKakiGuy** [comment]
Ok, got it working now, nice :D

**Comment by ThatKakiGuy** [comment]
Created a PR: #27
