### ISSUE TITLE
Bypass players spoofed values

### ISSUE THREAD

**Issue by Vlhss** [Yimura/YimMenu#250]
**Is your feature request related to a problem? Please describe.**
Not a problem but a useful addition.

**Describe the solution you'd like**
Since basically every menu has spoofing options (name, ip, rid, etc) it has become a pain in the ass to detect actual Rockstar moderators in order to either identify them and leave the session or have a build in system that automatically triggers a network bail.

**Provide Reasoning**
So my request is to bypass the spoofed values people have set and get their real credentials in order to verify if that is actually a real spectator or just a random dude with a p2c loaded attempting to avoid other modders.

**Additional context**
I want to avoid getting network bailed from lobbies when loading online since it takes ages to load while also keeping anyone's account safe

**Comment by maybegreat48** [comment]
Now that I think about it, how do the admins ban you anyway? The game is P2P and you can spoof your name, SCID, can use a VPN to hide IP address, hook presence stuff to prevent the session token being sent to Rockstar etc. Are you essentially invulnerable to manual bans if you spoof everything?

**Comment by Yimura** [comment]
That's a great question @maybegreat48, there are multiple ways I look at it.

1. You log into your account at one point, connect to the "session manager" and ask to join a random session that fits your search (min players, max players, region, pool). Now I don't know if this session manager requires authentication but if it does they must know which session they've given you or do they? Then from another standpoint, you create a new public session. There's something that announces to the "session manager" that you've created the session and how people should join this session.
2. R* Admin knows you're in session X because you communicated that with the session manager, maybe they don't do a targeted join but instead do a reverse lookup on the session manager to find the host of your session (though that is exactly what they do but maybe without asking your client directly but instead using the session manager). Ok so they get into your session but you have your values spoofed, what now? They joined the session you're allegedly in, there are many players, how will they find find you? Maybe they blame their system for being bad because they can't find you and assume they got booted to a different session? 

In my opinion, I think it's insanely hard to manual ban someone that isn't session host (thus being revealed by the session manager), though who can trust the session manager, you can most likely spoof values here as well (if Rockstar is stupid). So at that point they've got nothing to go of off.

Only thing you can 100% find out is the IP someone communicates from to your session.

Ps. I wrote my thoughts out.

**Comment by DaniTRDev** [comment]
> Now that I think about it, how do the admins ban you anyway? The game is P2P and you can spoof your name, SCID, can use a VPN to hide IP address, hook presence stuff to prevent the session token being sent to Rockstar etc. Are you essentially invulnerable to manual bans if you spoof everything?

Theorically you should be. But there are some fields in the CNetGamePlayer that also contains RID which aren't on public "reClass releases" I think Imp used one of those "hidden" fields to retrieven the non-spoofed values of players. I also remember something related to GTA sending out your account information to the server when joining (it isn't public but it is there). So I  assume it would be as easy as telling the server (through an admin-account) to give you the account details (email, CD-KEY, ...) and then retrieve the real information to apply the ban. 


Edit: The last part might be completely wrong but it rings me a bell it was like that. I've not been in GTA:O modding for a year or 2 now (1.52-1.54?).

**Comment by maybegreat48** [comment]
Yes I realized a while back that hooking send_net_info_to_lobby alone won't hide RID. Basically every script event, netevent, packet that sends a `rage::rlGamerHandle` is leaking your actual RID. There are some interesting messages like MsgConfigRequest and MsgQosProbeRequest (this one had its RTTI stripped) that could be what you are mentioning however I don't think rockstar is stupid enough to give random players email addresses and CD keys (they could maybe send hashed versions not sure haven't really researched these things before)

**Comment by DaniTRDev** [comment]
Nono, I wanted to mean that R* admins could have someshort of privilege in the server that is hosting the session and ask for this data. Of course that R* is not enough to give this to every player(at least that we know, R* keeps surprising me through every update). Although, as I said, I may be tripping with the shit I said but I swear it rings me a bell that they sent this type of data to the session-server. Also, a friend once told me that hooking the function that calls send_net_infi_to_lobby could get your RID 100% spoofed, not sure though. It is integrity checked because IIRC there was a RCE there.

**Comment by maybegreat48** [comment]
You can try hooking `48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 4C 89 70 20 55 48 8B EC 48 83 EC 40 48 8B F1 48 8D 4D E0 4D 8B F1 41 8B D8 48 8B FA` (integrity checked now but wasn't in 1.58?) and spoof the RID from gamer handle there. Of course this isn't 100% perfect, what your friend mentioned was probably hooking WriteBitsSingle which is also integrity checked (though I am a bit curious about that RCE you mentioned)

**Comment by Yimura** [comment]
As per the recent update it has become impossible to spoof RID/Username so there's no need for this issue to remain open.
