### ISSUE TITLE
please add new plates and foge LSC model [Improvement]: 

### ISSUE THREAD

**Issue by jvsandhu** [Yimura/YimMenu#2593]
### Which feature

please add new plates to the vehicle customization 
and can the modedest menu feature called "forgeLSC model" be added to the yim if possible 

### Reason

wan't them shinny new plates and the other one is value adon

**Comment by pierrelasse** [comment]
The plates SHOULD be automaticly added since they are retreived from the cache but maybe something else has to be done to be able to use them.
For the Forge LSC model. That would be cool to have tho you can already go in Vehicle->LS Customs and there press 'Start LS Customs' which is very buggy and makes everything bad.

**Comment by lonelybud** [comment]
refer https://github.com/YimMenu/YimMenu/pull/2524 i think ls custom now support somthing similar to Forge LSC model. Looks risky though.

**Comment by jvsandhu** [comment]
hmm so just get a car start LSC and then drive into LSC is that how it works
