### ISSUE TITLE
[Improvement]: Aimbot

### ISSUE THREAD

**Issue by Trapaceiro** [Yimura/YimMenu#2701]
### Which feature

Phantom Menu (by @[zdation1](https://www.unknowncheats.me/forum/members/2272198.html)) had the best aimbot I had never seen before... It was very clean, fast and accurate, with even a prediction option!
Is there any possibility to officially incorporate it into Yimmenu?

![Captura de tela 2024-02-10 202546](https://github.com/YimMenu/YimMenu/assets/17458432/32cf2f20-495a-4804-9d1a-b63e770d2ea0)

### Reason

- Better accurate
- Customizing toggle key to activate
- Prediction option
- Choose aimbot lock (Head, Neck or Stomach)

### Additional context

A few years ago he added the source code for download...
[Phantom Source](https://www.unknowncheats.me/forum/downloads.php?do=file&id=34825)

**Comment by gir489returns** [comment]
Very interesting source!!!!

@maybegreat48 and I had tried to reverse engineer how the game's camera works, it seems these guys figured it out! He's directly setting the view angles from pGameCamManager->pMyCameraManagerAngles->pMyCameraAngles. There seems to be varying different cameras for both vehicle, on foot (3rd person), and then the first person camera.

I think this may solve our aimbot problems. When I get some time, I will look into this. Thank you for showing this to us!

**Comment by gir489returns** [comment]
@Trapaceiro Some update on this. The source code is absolutely atrocious to read. I won't bore you with the details, but it is absolutely incomprehensible. I've sent a (very long) message request to the OP of the source code asking for clarification on his code. I seriously doubt I'll get a response, because he was last active on UC in November.

**Comment by rkwapisz** [comment]
I don't know how much help this will be, but a few years ago I did some work on the Enhanced Native Trainer and tried to implement an aimbot as well; I never merged the work into master since I never felt it was complete. I met with some reasonable success, but I got burned out trying to understand how the in-game cameras are handled. The aimbot worked well on-foot, but in a vehicle it was aiming above or below the target with a magnitude related to the overall size of the vehicle the player was in.

Like you, I concluded that there are different cameras being used depending on whether the player is in 1st-person, 3rd-person, or in a vehicle.

Feel free to dig around some of my math. I don't think any of it is revolutionary but I feel I was *so close* to getting a usable, reliable aimbot implementation if only I could find the "correct" camera to use. It's been a while, though, so I don't remember too much. At the time I did my best to keep things well-documented. You can even see some of the code I commented out as I experimented with the different cameras.

https://github.com/rkwapisz/GTAV-EnhancedNativeTrainer/blob/master/EnhancedNativeTrainer/src/features/aimbot_esp.cpp

More than anything I'm just curious to see what the optimal solution is. It's always been a bit of a drag on me having left this in an unfinished state with unanswered questions.

**Comment by gir489returns** [comment]
@Trapaceiro We attempted to implement this with https://github.com/YimMenu/YimMenu/pull/2902 however the code is worse than what we have now. The visibility checks they use are inconsistent, it still has the same problem of aiming too high over peds too far, and the code is an absolute mess.

**Comment by gir489returns** [comment]
@rkwapisz The repo you tagged is private we can't access it.

**Comment by FIying-Scotsman** [comment]
> @rkwapisz The repo you tagged is private we can't access it.

These should hopefully work:-

[ENT - aimbot_esp.zip](https://github.com/YimMenu/YimMenu/files/14828330/ENT.-.aimbot_esp.zip)

**Comment by rkwapisz** [comment]
Thanks, @FIying-Scotsman. It's good to see you again. I remember collaborating with you on ENT.

I've made some good progress with the overall Yim aimbot logic (scanning, targeting, some simple prediction) based on my earlier ENT implementation, but the keystone of a solid implementation relies on understanding how the gameplay camera works and how it can be manipulated to correctly aim when the player is in a vehicle. The aimbot is able to correctly calculate the horizontal angles, but it tends to aim too low corresponding in some way to the size of the player vehicle.

Basically, manipulating gameplay camera pitch via the SET_GAMEPLAY_CAM natives behaves differently when the player is in a vehicle. I believe the Phantom developer(s) discovered this early on which is why they resorted to patching the camera coordinates directly via offsets. I also believe this is why Phantom has a "horizontal aim" only option as it's also something I explored with ENT; if we couldn't get perfect aim in a vehicle, at least we could make it easier for the player some way.

What's funny, and somewhat frustrating, is that there are natives that handle other non-gameplay cameras that would solve the issue. Just imagine how trivial an aimbot would be if POINT_CAM_AT_PED_BONE worked with the gameplay camera...

Offsetting the player's gameplay camera location's z-coordinate provided some minor improvement, but the aiming angles would be inconsistent across different x/y ranges and the size of the player's vehicle. Basically, you could fine-tune the aimbot to provide decent headtracking in a particular car at short to medium range, but the offset would have to again be adjusted if the player entered a different car or the target way too far away. It was never an ideal solution.

I think patching camera coords directly might be the optimal solution. If we figure out how to do that, rolling it in with the rest of the targeting and tracking logic is trivial.
