### ISSUE TITLE
[Bug]: Force Host locks the lobby

### ISSUE THREAD

**Issue by snowleopardd** [Yimura/YimMenu#2760]
### Describe the bug

Whenever i use the "force host" and kick the guy, no one joins the lobby then people start leaving and it dies.

### Steps To Reproduce

1- inject the menu
2- enable "force session host"

### Expected Behavior

the lobby shouldn't get bugged and people would be able to join

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

Spanish

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by passionfr7it** [comment]
where is the log

**Comment by mikedrugs** [comment]
> where is the log

no need to post logs, try it yourself and it will happen

**Comment by snowleopardd** [comment]
i can post it if you guys want but i dont know if it's gonna make any difference

**Comment by Rxann** [comment]
> i can post it if you guys want but i dont know if it's gonna make any difference

When posting a bug report, it is probably beneficial to post the log.

**Comment by Yimura** [comment]
When taking over the lobby you basically need to get lucky that the GTA V matchmaking servers bless you and see you as good lobby for people to join.

Do you have Block RID joining enabled perhaps? I haven't got a clue how exactly the matchmaking works and on what it relies...

**Comment by darkwanderr** [comment]
> When taking over the lobby you basically need to get lucky that the GTA V matchmaking servers bless you and see you as good lobby for people to join.
> 
> Do you have Block RID joining enabled perhaps? I haven't got a clue how exactly the matchmaking works and on what it relies...

Maybe it could be related to spoofing session attributes or forcing relay connections?

**Comment by snowleopardd** [comment]
So, I've been extensively testing spoofing attributes, relay connections, and changing globals.

Disabling force relay connections has shown improvement and seems to help significantly. People WILL join, BUT not enough to keep the lobby alive. So, I tried messing with the spoofing options, but nothing worked, You will lose more players than those who join, so the lobby will end up dead xD.

**Comment by TwystedMind** [comment]
The only time I've particularly noticed my sessions die after forcing Session Host, is when I change my session region or filter the session attributes (players in lobby, language, region) - basically anything outside of traditional matchmaking.  If you've ever used the Session Browser, verify that "Replace Matchmaking" isn't enabled.

I would also assume that Rockstar routes to Session Hosts with viable network quality to their servers, but I don't know that for certain.  Otherwise, I can't say I personally have had this issue enough to call it anything other than a one-off.  

Logs can actually be useful, because it can help determine if players leaving your session are receiving a specific NETWORK_EVENT to cause it.  Players could be timing out or being desync'd because of a poor quality connection to Rockstar.

**Comment by snowleopardd** [comment]
I'm closing this since a few days ago i found out that my router NAT type is "moderate", which seems like rockstar really hates, then we tested with a friend with yim and he could host normally with people joining (we are from the same country), so it's just me.

If you're seeing this and u got closed ports or stricted NATS and u wonder why you always lose players when u are the host, this is why.

**Comment by lonelybud** [comment]
have good NAT type, join good lobby, wait for your number to become host, dont spam host kick, wish that regional players around you start their games around your time or you are the only international host online in the world they can join and you are good to go.
