### ISSUE TITLE
[Improvement]: Compile Times

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#2840]
### Which feature

Compiling the project

### Reason

Currently, changing a single cpp file and reinjecting takes a solid 2 or 3 minutes of my life and makes it very difficult to develop new features. Is there anything we can do to drop this down to a sub-minute time-frame? Ideally even less but I guess the project has grown a lot.

### Additional context

Could we maybe have like a dev branch that is stripped of a lot of unnecessary components?

**Comment by gir489returns** [comment]
I had this issue on my 7th gen i7, but now that I have a 13th gen, I don't. Could just say: skill issue, but I really don't have this issue when using x64-Release-FastCompile. As the name implies, it doesn't use any of the optimizations (that in my opinion do fuck-all) and the compile times for me are about 2 seconds if I change a CPP, about 30 seconds if I change a header included by 10-20 CPPs. 1 minutes if it's by a few hundred. 2 minutes if I change a setting. 3 minutes for a complete rebuild.

**Comment by Tayipc38** [comment]
> I had this issue on my 7th gen i7, but now that I have a 13th gen, I don't. Could just say: skill issue, but I really don't have this issue when using x64-Release-FastCompile. As the name implies, it doesn't use any of the optimizations (that in my opinion do fuck-all) and the compile times for me are about 2 seconds if I change a CPP, about 30 seconds if I change a header included by 10-20 CPPs. 1 minutes if it's by a few hundred. 2 minutes if I change a setting. 3 minutes for a complete rebuild.

Im rocking a ryzen 7 5800x. It aint the best but it should suffice no?

**Comment by xiaoxiao921** [comment]
There are definitely issues with compile times right now, you can try using build insight from Visual Studio and investigate thoroughly what is taking so much time

**Comment by gir489returns** [comment]
> Im rocking a ryzen 7 5800x. It aint the best but it should suffice no?

From what I've heard, MSVC is optimized for intel. Every time AMD promises big returns (including the Ryzen) it always ends up being a marketing campaign that fails. Bulldozer in particular. While I don't know much about the Ryzen series, google tells me it's almost exactly similar to the i7-7700K that I had before.

That being said, I dropped $2.5Gs (on sale) for a prebuilt computer with a 4090. I kinda regret it, because all it really did was reduce compile times (which were agitating me at the time, but wasn't worth the money) and I thought RTX would  be super cool, but it seems like a giant meme. Portal RTX was a lie. I thought they were dynamically drawing the light and surface textures at runtime, they fucking cheated and did asset injection. Take a 20 year-old game, get some art student to make modern assets, BAM shiny looking game.

All that nonsense being said: I think the compile times are fine as-is, although if someone wants to play CI engineer to this project and its 50 fucking dependencies, they're more than welcome to I guess.

**Comment by Tayipc38** [comment]
> All that nonsense being said: I think the compile times are fine as-is, although if someone wants to play CI engineer to this project and its 50 fucking dependencies, they're more than welcome to I guess.

Had my fingers crossed for exactly this when making this issue.

**Comment by Tayipc38** [comment]
Fast compile does boast a significant difference.

**Comment by gir489returns** [comment]
> Fast compile does boast a significant difference.

I figured you were using the regular Release compile mode. It defaults to that when you open the project. It makes a monumental improvement on compile times. The only downside is the bloat of the file. Makes it like 32MBs or something compared to the release mode 12MBs.

**Comment by Tayipc38** [comment]
Switch to Fast compile to be able to, you know, compile fast.
