### ISSUE TITLE
Building fail Error MSB3721	The command "ml64.exe /c /nologo /Zi /Fo"..\bin\int\Release\BigBaseV2\invoker_asm.obj" /W3 /errorReport:prompt  /Tasrc\invoker_asm.asm" exited with code 1.

### ISSUE THREAD

**Issue by unkmonster** [Yimura/YimMenu#286]
**Describe the bug**
Can't build Error MSB3721

**To Reproduce**
1. x64 release build
2. build fail

**Expected behavior**
successfully build

**Logs**

```
<paste your logs here>
Severity Code Description Project File Line Suppression State
Error MSB3721 The command "ml64.exe /c /nologo /Zi /Fo"..\bin\int\Release\BigBaseV2\invoker_asm.obj" /W3 /errorReport:prompt /Tasrc\invoker_asm.asm" exited with code 1. BigBaseV2 D:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\masm.targets 70
```

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
I try to build the project, but visual studio spit out this error.

**Comment by Yimura** [comment]
Sadly I do not have enough information to work here, is there more build log than this one line?
Did you modify any files? Because a clean clone of YimMenu should not produce this error.

From the Microsoft docs:
![IMG_2825.png](https://user-images.githubusercontent.com/24669514/175757490-a73ad9b5-96b4-46ad-a5b1-0848b2aa46b8.png)

**Comment by unkmonster** [comment]
thx It's my computer coding problem, now successfully builded. I set the coding of my computer to utf-8 before
