### ISSUE TITLE
该如何使用

### ISSUE THREAD

**Issue by Mobsterhh** [Yimura/YimMenu#2896]
I really wanted to use it, but after working on it for a long time, I didn't quite understand the results. At first, I came up with a menu, but I couldn't understand it. I looked for a translator to see if it was there. When I found it and tried it again, I still don't know how to open the menu. The menu options have changed, and I don't know what the situation is. I suggest a tutorial. Thank you, I will always support you

**Comment by BigboiKilljoy** [comment]
Have you ever considered speaking English?

**Comment by BigboiKilljoy** [comment]
Can we kick this dude out of here for leaving the job of translation up to us?

**Comment by Mobsterhh** [comment]
I really wanted to use it, but after working on it for a long time, I didn't quite understand the results. At first, I came up with a menu, but I couldn't understand it. I looked for a translator to see if it was there. When I found it and tried it again, I still don't know how to open the menu. The menu options have changed, and I don't know what the situation is. I suggest a tutorial. Thank you, I will always support you

**Comment by gir489returns** [comment]
@sch-lda Do you think you could help this guy out?

**Comment by sch-lda** [comment]
@Mobsterhh  确实有一个傻瓜式的工具能为你一键注入Yimmenu https://github.com/CrazyZhang666/GTA5OnlineTools/releases/tag/update
@Mobsterhh  There is indeed a simple tool that can inject Yimmenu with just one click. https://github.com/CrazyZhang666/GTA5OnlineTools/releases/tag/update

> @sch-lda Do you think you could help this guy out?

maybe

**Comment by sch-lda** [comment]
> @sch-lda Do you think you could help this guy out?

~~Due to the poor translation, I cannot understand what problem he is describing, nor can I determine if it is related to build.~~( I found his original Chinese post )
I think he just doesn't know how to inject, or encountered problems when downloading the Chinese language files based on issue's title "该如何使用"

@Mobsterhh 如果你遇到编译相关问题，请留下你的联系方式。否则请描述清楚具体是在哪一步遇到了什么问题。如果你什么都不想做，也可以尝试这个傻瓜式工具注入Yimmenu，它会为你免除手动使用注入器和为yimmenu设置代理的麻烦 https://github.com/CrazyZhang666/GTA5OnlineTools/releases/tag/update

如果你不知道如何显示菜单，显示和隐藏菜单的默认快捷键是 Insert
如果中文语言文件无法下载，你需要为Yimmenu设置代理(Settings-Proxy Settings)，填写你的clash/v2ray代理信息。或者使用tun模式进行适配器级代理，注入成功后再关闭

(@Mobsterhh If you encounter any build-related issues, please leave your contact information. Otherwise, please clearly describe where and what problem you encountered specifically. If you prefer not to do anything, you can also try this user-friendly tool to inject Yimmenu, which will save you the trouble of manually using an injector and setting up a proxy for yimmenu: https://github.com/CrazyZhang666/GTA5OnlineTools/releases/tag/update)

The default hotkey to show and hide the menu is Insert.
If the Chinese language file cannot be downloaded, you need to set up a proxy for Yimmenu by entering your Clash/V2Ray proxy information ((Settings-Proxy Settings)). Alternatively, you can use tun mode for adapter-level proxying, after injection ,you can close TUN mode.

**Comment by xiaoxiao921** [comment]
@sch-lda original message


弄了大半天，结果不会用，一开始还弄出来了菜单 ，结果看不懂，来这里找翻译看看有没有，找到了回去用结果一直不知道怎么开菜单了，菜单选项还变的不一样了不知道什么情况，建议出个教程，感谢各位大佬，可以请喝水

**Comment by sch-lda** [comment]
> @sch-lda original message
> 
> 弄了大半天，结果不会用，一开始还弄出来了菜单 ，结果看不懂，来这里找翻译看看有没有，找到了回去用结果一直不知道怎么开菜单了，菜单选项还变的不一样了不知道什么情况，建议出个教程，感谢各位大佬，可以请喝水

I see, but there is still a lack of useful information. I can only provide two possible solutions.

**Comment by gir489returns** [comment]
It has been a week since this ticket was created, and since the user has not delivered more information, I'm going to close the ticker.
