### ISSUE TITLE
[Request]: Block all Crashes from Cherax

### ISSUE THREAD

**Issue by Ahmad23145** [Yimura/YimMenu#3101]
### Problem

I got crashed from cherax 

### Solution

Fix/Patch the crashes pls 

### Reason

bc i hate being crashed

### Additional context

[cout.log](https://github.com/YimMenu/YimMenu/files/15287152/cout.log)

**Comment by gir489returns** [comment]
@xiaoxiao921 I didn't have a lot of time to look at this, but it's crashing somewhere in hooks::scripted_game_event.

**Comment by rkwapisz** [comment]
Could probably use a sanity check for scripted_game_event before trying to access elements in m_args.

**Comment by gir489returns** [comment]
> Could probably use a sanity check for scripted_game_event before trying to access elements in m_args.

That would mean that m_args was null somehow, which doesn't make sense. CScriptedGameEvent gets constructed on the previous function call, which is then populated by ReadDword and ReadArgs.

I'd love to introspect the DLL he used, but because he is using a dirty branch, and also not using the proper Yim deployment, this user is now responsible for this ticket, thus we are going to close it. If he can replicate it on the Release branch or even just a PR DLL, then we will take another look. But not with this half-assed bullshit "bc i hate being crashed" nonsense ticket, he has to properly fill out the ticket.

**Comment by Ahmad23145** [comment]
[YimMenu.zip](https://github.com/YimMenu/YimMenu/files/15287437/YimMenu.zip)
In this zip u can find my dll

**Comment by rkwapisz** [comment]
> > Could probably use a sanity check for scripted_game_event before trying to access elements in m_args.
> 
> That would mean that m_args was null somehow, which doesn't make sense. CScriptedGameEvent gets constructed on the previous function call, which is then populated by ReadDword and ReadArgs.

I see what you mean, but I am wondering whether we are pulling valid data from the buffer and, at the risk of vastly overstepping my knowledge of the game code, do we know if/how the game validates the buffer before we intercept it?

This question is moreso for my own knowledge. I've never seen this user's particular crash before and I have no idea how they can verify that it was caused by another menu.
