### ISSUE TITLE
[Request]: Banning the use of certain vehicles

### ISSUE THREAD

**Issue by opt8** [Yimura/YimMenu#3333]
### Problem

Hello. It would be great if the menu could, at least by the icon on the minimap, react to certain types of transport

### Solution

If the menu notices a "banned" type of transport, then, for example, it kills its engine, or any other action to choose from

### Reason

Some trolls on oppressors or rc-tanks and other types of transport interfere with the game and disturb other players

**Comment by iwanttodo1t** [comment]
Some people think that such a function infringes on the rights of other players.

**Comment by gir489returns** [comment]
I used to have a feature for this called Eat Spaghettios on Mod Sobiet V which translated into Eat MK2 Oppressors on BBv2.

https://bitbucket.org/gir489/bigbasev2/src/4dd1da37d335daa235d35f40a9e478e34fa6f276/BigBaseV2/src/features.cpp?at=master#lines-457

There's nothing from within that code that can't be done in the Lua layer, so we're not going to be adding this, especially since this is a toxic feature, and the menu is hypocritical enough trying to portray itself as protection from toxic modders while simultaneously having toxic features.
