### ISSUE TITLE
[Request]: More options on other players

### ISSUE THREAD

**Issue by iskidfromAddict** [Yimura/YimMenu#3372]
### Problem

Not related to a problem!

### Solution

More features under the network solution related to the session and players in the session

### Reason

Sometimes I get a bit bored and want to help the session or troll a toxic troll for a little bit

**Comment by Yimura** [comment]
This is issue is too ambiguous, there is no specific content requested as such it's really just a garbage issue that will never end up being closed.

Because:
1. When are there "enough" features implemented
2. No specific feature is requested (except for that it needs to be specific to network)

As such I'll close this, these features will come automatically over time as people make things. In general we don't make new features that are "too simple" to implement in YimMenu. As such I'd look into just installing some Lua files from https://github.com/orgs/YimMenu-Lua/repositories.

**Comment by iskidfromAddict** [comment]
oh sorry about that !! ill take that into consideration if i request next time sorry bro 👍
