### ISSUE TITLE
[Build]: menu no workie, me stupid, HELP

### ISSUE THREAD

**Issue by ahhhhh65** [Yimura/YimMenu#3426]
### Describe the build issues

i don't know what to do or how to get this working i put the dll in the game file and it didn't work, if its too complicated to just say so i dont feel like do 10 million steps just to most likely get banned. 

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by howdoiusekeyboard** [comment]
dll in the game file?? you have to inject it using an injector bro.
Use https://github.com/DarthTon/Xenos

**Comment by CypherMorgan** [comment]
Place the dll you downloaded in a specific directory ( Not the Game's Main Directory ), Download the Xenos injector from the Link above and add an Exclusion for both (DLL and the Injector) in your Anti-Virus so that it doesn't deletes it assuming it's a Virus. Boot up your game and open Xenos, select game's process (GTA5.exe) click on Add, select the DLL file, then inject the menu. Once it's loaded, Allow it to Generate the Cache. Now you can use your menu. (The default keybind to open the menu is INSERT on the Keyboard)
I hope this helps.

**Comment by ahhhhh65** [comment]
thank you it was 1am and i didn't feel like reading
