### ISSUE TITLE
[Bug]: coloading menu (duplicate issue)

### ISSUE THREAD

**Issue by juhannnnnn** [Yimura/YimMenu#3455]
### Describe the bug

I am using both Yimmenu and Cherax mod menu together(coloading). i admit that this is a complicated mess by trying to use both menus together. It is honestly because i want to combine the benefits of both the menus. however i have found that while both menus work concurrently good initially, after sometime the issues i mentioned in the title begin to appear.

### Steps To Reproduce

1) Launch gta 5
2)Load Cherax menu
3)Load Yimmenu by using Xenox injector
4) once in game, try using the super hero fly option from Yimmenu and spawn ped and spawn new vehicle options.

### Expected Behavior

both the menus should work concurrently fine without conflicting each other's functions.

### Logs

[cout.log](https://github.com/user-attachments/files/16402525/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I would also like the unload option to instantly unload yimmenu.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [ ] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
You kind of need to test these features without co-loading. That’s why we require people to submit issues to cross the checkbox that they’ve tested it without co-loading.

We can’t know why Cherax is breaking YimMenu and I’m definitely not going to bother figuring out why it isn’t working.

If something breaks because of co-loading then you’re pretty much on your own.
