### ISSUE TITLE
[Request] UNLOAD OPTION

### ISSUE THREAD

**Issue by juhannnnnn** [Yimura/YimMenu#3456]
### Problem

it becomes quite inconvenient for me to not be able to unload yimmenu when i want to.

### Solution

Please add the Unload option.

### Reason

For convenience and security.

**Comment by Yimura** [comment]
We don’t allow unloading because it’s dangerous to do so if you don’t know what you’re doing. The game might have detected something and you’re being kept safe as long as you keep YimMenu injected. The moment you unload that protection is gone. 

Neither is your reasoning very clear, “convenience”, what’s inconvenient about keeping YimMenu loaded? If there is make an issue about what that is (Tell us if a mission breaks, an interior is unusable, etc…). “Security”, see my earlier reasoning, you may get banned for detections being sent out after unloading YimMenu.

**Comment by juhannnnnn** [comment]
oh ok i get it but didn't yimmenu once have the unload option? As i think you may remember i wanted to use it concurrently with Cherax. I thought unloading yimmenu and then reinjecting it might solve some of those problems i mentioned.

**Comment by Yimura** [comment]
Yes it used to have it, it’s only available for developers currently as they know the danger of unloading the menu. We removed it normal users as there really shouldn’t be a reason to unload YimMenu. 

As you’re co-loading you’re basically on your own to fix these issues.

If you wish to have an unload button then you’ll need to build your own version of YimMenu locally to enable it. However remember that you should only ever unload in single player and even then it could be risky.

**Comment by juhannnnnn** [comment]
Alright I get it. Thank you.
