### ISSUE TITLE
[Request]: Github Action to generate JSON formatted list of the YimLua org

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#3507]
### Problem

In order to build an in-menu Lua Workshop, we need actionable data. Since the repos know no limit (nor does their content), querying Github with countless http requests does not bode well due to the rate limitation on Githubs API system.

### Solution

Create a Github action that generates a certain JSON file which contains all necessary data, and keeps itself updated each time a repo has a change.

### Reason

Because Im going to build an in-menu lua work-shop.

### Additional context

@Yimura do ur git magic baby.

**Comment by Tayipc38** [comment]
If I hear anything about this ticket being out of place, I will commit crime.

**Comment by xiaoxiao921** [comment]
> Create a Github action that generates a certain JSON file which contains all necessary data, and keeps itself updated each time a repo has a change.

Proceed to not give a json sample

**Comment by gir489returns** [comment]
> If I hear anything about this ticket being out of place, I will commit crime.

Of the N variety?

**Comment by xesdoog** [comment]
@DayibBaba Sorry, I know this was closed but I love the idea. I did something a bit similar in Python and got around the rate limit by caching the response using requests-cache. My friend and I ended up scrapping the idea and the launchpad now simply opens the org in a browser instance instead of showing the scripts and allowing the user to download them. The project is open source so if you're interested I'll send you a link.
