### ISSUE TITLE
[Bug]: Microsoft Defender keeps spamming me with "A threat has been found"

### ISSUE THREAD

**Issue by DawTheD** [Yimura/YimMenu#3605]
### Describe the bug

Since I have downloaded the latest nightly version (as of 19.08.24), I keep getting spammed by Microsoft Defender

### Steps To Reproduce

1. Download YimMenu.dll
2. Allow download
3. Microsoft Defender should do its thing once enabled

### Expected Behavior

Microsoft Defender keeps saying a virus has been detected (e.g. Trojan)

### Logs

[cout.txt](https://github.com/user-attachments/files/16670171/cout.txt)

### Store

Rockstar

### Language

Polish

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
https://github.com/YimMenu/YimMenu/discussions/3504

**Comment by ghost** [comment]
Dumb ass Issue ngl. Make an exception thats it. Ofc a dll gets flagged as a Virus and an injector gets too.

**Comment by gir489returns** [comment]
> Dumb ass Issue ngl. Make an exception thats it. Ofc a dll gets flagged as a Virus and an injector gets too.

Shut the fuck up. When I was a pentester, I can't tell you how many times an entire enterprise network got infected because some retard just clicked on a virus EXE I sent them, and then listened to the fact the e-mail said to turn off their enterprise endpoint security suite. Telling people "LE HECKIN HACKING SOFTWARE IS SAFE, IGNORE DEFENDER" is the most dumbass piece of fucking advice ever. There's tons of scammer/fake videos on YouTube that claim to be our project with links to malware, and what do people do on the official project site? Deride and conject about anti-virus being wrong. It's absolutely appalling.

There's a reason it's detecting YimMenu as a virus. Because 9/10 times, it probably fucking is.

**Comment by DawTheD** [comment]
> > Dumb ass Issue ngl. Make an exception thats it. Ofc a dll gets flagged as a Virus and an injector gets too.
> 
> Shut the fuck up. When I was a pentester, I can't tell you how many times an entire enterprise network got infected because some retard just clicked on a virus EXE I sent them, and then listened to the fact the e-mail said to turn off their enterprise endpoint security suite. Telling people "LE HECKIN HACKING SOFTWARE IS SAFE, IGNORE DEFENDER" is the most dumbass piece of fucking advice ever. There's tons of scammer/fake videos on YouTube that claim to be our project with links to malware, and what do people do on the official project site? Deride and conject about anti-virus being wrong. It's absolutely appalling.
> 
> There's a reason it's detecting YimMenu as a virus. Because 9/10 times, it probably fucking is.

Hold up dude, if you're a contributor then 9/10 times you should know if something is a virus or not.
