### ISSUE TITLE
[Improvement]: The input box cannot input Chinese, but can paste

### ISSUE THREAD

**Issue by Liuchun-oss** [Yimura/YimMenu#3613]
### Which feature

ImGui:input box

### Reason

The input box cannot input Chinese characters. If you want to input Chinese characters, you can only copy them from other places and then paste them into the input box.

**Comment by gir489returns** [comment]
This is probably because our WndProc hook only accepts ASCII characters not UTF-8, this is probably an issue for Russian and Turkish too.

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/master/src/renderer/renderer.cpp#L111-L118

We just pass the WndProc straight to ImGui which does

https://github.com/YimMenu/imgui/blob/master/backends/imgui_impl_win32.cpp#L617-L630

So I guess it checks if the GTA V process is Unicode or ASCII, and if it's not, then it refuses to get Unicode from the window.

**Comment by Yimura** [comment]
The YimMenu/imgui repository is no longer used but I'm guessing that the `imgui_impl_win32.cpp` file is still the same in the current version of ImGui.

**Comment by gir489returns** [comment]
![image](https://github.com/user-attachments/assets/5eaf0dc5-5102-4db3-9fc3-476719a197a4)

When the menu is in English mode, it refuses to accept other characters (because we've made it not load other fonts)

However, once I put YImMenu RU-ru mode, it allowed me to type Russian characters from my keyboard. @Liuchun-oss Do you have YImMenu running in Chinese mode?

**Comment by gir489returns** [comment]
@sch-lda I can't imagine you've been using the menu for this long and haven't noticed this. Can you shed some light on this issue?

**Comment by sch-lda** [comment]
> @sch-lda I can't imagine you've been using the menu for this long and haven't noticed this. Can you shed some light on this issue?

Chinese characters cannot be directly input via the keyboard, they must be converted from letters to characters using a Chinese input method like Microsoft Pinyin. 
![image](https://github.com/user-attachments/assets/a4e8a947-f596-41e0-b485-97c649d5adc1)
The issue is not with Yimmenu or ImGui. I believe that GTA V may have implemented some interference with Chinese input. GTA V always switches the input method to en_us, and only when the in-game chat input box is open can the Chinese input method be activated. Additionally, the Chinese input method cannot render its interface over GTA's window. Even when I hook the Windows API ActivateKeyboardLayout to prevent the game from changing the input method, the interface of the Chinese input method still doesn't render on the game. 
When entering text in the GTAO chat input box, the displayed candidates are not from the input method's candidate window but are drawn by GTA, regardless of the input method used. However, the candidate words themselves do come from the third-party Chinese input method. I suspect that GTA V might be using the Text Services Framework or other interfaces to retrieve Chinese candidate words from the input method while disabling the input method's own operational logic.
![image](https://github.com/user-attachments/assets/c4f294e3-d773-485f-95ff-dc4a64948806)

GTAV might do this because most Chinese input method overlay cannot render in fullscreen games unless injecting. I noticed that a P2C menu took advantage of GTA's built-in Chinese input mechanism, using GTA-proxied Chinese input method and display the results in the menu's input box. This might require reversing how GTAV handles Chinese input.
