### ISSUE TITLE
[Bug]: Exception When Calling Original Function in `dynamic_hook`

### ISSUE THREAD

**Issue by ShinyWasabi** [Yimura/YimMenu#3664]
### Describe the bug

Calling the original function in Lua `dynamic_hook` by returning true in the detour leads to exception.
Example Code:
```lua
local add_content_item_lock = memory.scan_pattern("85 D2 0F 84 ? ? ? ? 48 8B C4 48 89 58 ? 48 89 68 ? 48 89 70 ? 89 50")

local G9EC_LOCK_HASHES = {
    [joaat("CU_SUM24_CLOTHES_G9EC")] = true,
    [joaat("CU_SUM24_MASKS_G9EC")]   = true,
    [joaat("CU_X23_MASKS_G9EC")]     = true,
    [joaat("CU_X23_CLOTHES_G9EC")]   = true,
    [joaat("CU_SUM23_MASKS_G9EC")]   = true,
    [joaat("CU_SUM23_CLOTHES_G9EC")] = true,
    [joaat("CU_X22_MASKS_G9EC")]     = true,
    [joaat("CU_X22_CLOTHES_G9EC")]   = true,
    [joaat("CU_SUM2_G9EC_MASKS")]    = true,
    [joaat("CU_SUM2_G9EC_CLOTHES")]  = true
}

memory.dynamic_hook("add_content_item_lock", "void", { "int", "int", "int", "bool" }, add_content_item_lock,
function(ret_val, this, hash, a3, locked)
    local item_hash = hash:get()
    if G9EC_LOCK_HASHES[item_hash] then
        locked:set(false)
    end
    return true -- If you return false, it works fine.
end,
function(ret_val, this, hash, a3, locked)
end)
```
I've tested multiple functions, and they all triggered exceptions when attempting to call the original function.

### Steps To Reproduce

1. Set up a `dynamic_hook` function and return true to call the original function in the detour.

### Expected Behavior

The original function should execute without causing any exceptions.

### Logs

[cout.txt](https://github.com/user-attachments/files/16894239/cout.txt)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Does the problem still happen if you use the correct types for the parameters?

```
"int64_t", "int", "uint16_t", "bool"
```

**Comment by ShinyWasabi** [comment]
That fixed it, thanks. Shouldn't `int64_t` and `uint16_t` be considered as `int` anyway, since `get_type_info_from_string` returns `type_info_t::integer_` for them? That's why I was using `int`.

**Comment by xiaoxiao921** [comment]
My understanding is that the upper value of let's say the 64bit register might get trashed when you are in reality for example only using the 16 first low bits.

**Comment by gir489returns** [comment]
> That fixed it, thanks. Shouldn't `int64_t` and `uint16_t` be considered as `int` anyway, since `get_type_info_from_string` returns `type_info_t::integer_` for them? That's why I was using `int`.

This makes no sense, since the type_info_t is the returned Sol type. Since there is no integer type in Lua, it's actually called number (which in actuality also doesn't matter, since Lua won't let you strongly type things anyway) it's so the Sol converter knows what to emplace into Lua's memory so it can read it properly. 

Rule of thumb is: get it working first, then refactor and reduce.

**Comment by xiaoxiao921** [comment]
get_type_info_from_string do return integer no matter what for any int types but that's because this enum is exclusively used for lua type conversion. this array: `"int64_t", "int", "uint16_t", "bool"` used in the dynamic_hook call is specifically used for asmjit to generate the correct assembly when you are calling the original function and for the generated detour function to correctly handle the incoming parameters
