### ISSUE TITLE
[Bug]: ESP not showing health and armor of player

### ISSUE THREAD

**Issue by RainerZufall187** [Yimura/YimMenu#397]
### Describe the bug

The ESP does't show the health and armor bar on the left side of the box, even though it is enabled in the settings.

### Steps To Reproduce

Just have the default settings on the ESP tab

### Expected Behavior

Health- and Armor Bar showing up on the left side of the box

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/40537673/183306261-b01e0223-6be5-48c9-85d1-42cbbca1f010.png)

### Store

Rockstar

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Regression appears to have been introduced in #344

You can force the player health and armor to be visible again by disabling the "Show Player Godmode" feature.

The bug is from the following line `view_esp.cpp`:
https://github.com/YimMenu/YimMenu/blob/7760460b9e778c48187def2db24510befd8d7337/BigBaseV2/src/views/esp/view_esp.cpp#L89

Ped Damage bit always has a `value > 0`.
![image](https://user-images.githubusercontent.com/24669514/183307259-e9831a32-47d7-47ec-81fd-375ba427f9be.png)

This check can be fixed by applying a bit mask that filters out the following two bits:
```cpp
1 << 2 | 1 << 3
```

**Comment by Yimura** [comment]
Fixed by #401
