### ISSUE TITLE
Avoid copying of bool options to other selected Player

### ISSUE THREAD

**Issue by beast177** [Yimura/YimMenu#41]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like:**
I think by Adding class to Players will avoid copying of bool options to other **Selected Players**, for example if u select Freeze option On a selected **Player_A** it will only apply to that selected **Player_A**, and will not apply to Other selected **Player_B**.

**Provide Reasoning**
For Better Optimise Code, 

**Additional context**
None.

**Comment by Yimura** [comment]
Any example of such bools? As long as you make sure that these bools aren't saved to disk this shouldn't be a problem, same for the spectate bool.

Aside from that there's a place where you can reset variables inside the player_window.cpp file, this is only for when the player disconnects, you can add an if statement above that the checks if the player id of the selected player has changed that will reset certain variables.
https://github.com/Yimura/YimMenu/blob/04cdf96e809211e91d2f6ccd356d0735d757fb21/BigBaseV2/src/gui/window/window_player.cpp#L9-L14

As long as you have the code from https://github.com/Yimura/YimMenu/commit/bac623ed8b1e204221e9847039c4d66a91bc80ee then there should not be a problem. Although I agree that the current methodology for keep track of player information is not ideal and would be better the switch to pointer than copying the selected player. (one of the remnants of when I didn't really understand C++)

**Comment by Yimura** [comment]
I've completely rewritten how player data is managed in the current code base, good luck with updating your menu!

The player class has a function with which you can check if the underlying player data is valid.
https://github.com/Yimura/YimMenu/blob/cadb083d5f9056b1c242031a4582ff8c54f8cf0f/BigBaseV2/src/services/player_service.hpp#L6-L32

Example code where I check if the player is still connected:
https://github.com/Yimura/YimMenu/blob/2f4838bc1407440f333c25fee553585530b3b151/BigBaseV2/src/backend/looped/player/spectate.cpp#L12

For now the list with players that are your friends has been removed...

**Comment by beast177** [comment]
Thanks! I'll apply your recent commits, cuz in other menus, like Stand I've seen that certain options do not copy over to the next Selected player like spectating, syncs and other stuff..

**Comment by Yimura** [comment]
I've further simplified how players are handled in the menu, you just use the player_service and call get_selected() which will return a player. If no player was selected this will still return a dummy player instance from which you can call the functions they just all return default values.

So instead of:
https://github.com/Yimura/YimMenu/blob/2f4838bc1407440f333c25fee553585530b3b151/BigBaseV2/src/backend/looped/player/spectate.cpp#L12

You can just:
https://github.com/Yimura/YimMenu/blob/927203b844a91b8256857424434e979210782959/BigBaseV2/src/backend/looped/player/spectate.cpp#L12


Also if you want to reset player values on disconnect you can do so here:
https://github.com/Yimura/YimMenu/blob/927203b844a91b8256857424434e979210782959/BigBaseV2/src/services/player_service.cpp#L145-L146

If you want to reset player values on switching you can do so here:
https://github.com/Yimura/YimMenu/blob/927203b844a91b8256857424434e979210782959/BigBaseV2/src/gui/window/window_users.cpp#L19-L24
