### ISSUE TITLE
[Bug]: Weird number on top of screen

### ISSUE THREAD

**Issue by rxcf** [Yimura/YimMenu#427]
### Describe the bug

This number "1.58.07" just came out of nowhere and its not in code. It only shows up when i inject yimmenu

### Steps To Reproduce

No idea

### Expected Behavior

No idea

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/80929479/187079402-2085636a-6f5c-4353-9f36-d02d2ee9cac2.png)

### Store

Rockstar

### Build

- [X] I used YimMenu unmodified

**Comment by maybegreat48** [comment]
This is most likely caused by the detected `IS_DLC_PRESENT` hook that some commit I cannot find re-enabled
That hook enables "developer mode" which causes the background script to display its version, this is generally seen only in the clouds but it continued to remain in the session for you for some reason

**Comment by Yimura** [comment]
#399 is the culprit

with #420 to keep track of changes to this.
