### ISSUE TITLE
[Question]: Failed to find native's handler

### ISSUE THREAD

**Issue by Sheeeeit** [Yimura/YimMenu#448]
I **inject** into the game directly while in **singleplayer**, but I still get these warnings. I would like to know the consequences of this error and whether it can be somehow fixed? ([Picture](https://i.imgur.com/4nwp9OC.png))

Before the previous two code changes, such errors did not appear.
I don't know which category to put this problem in, so I'll create it here

**Comment by Yimura** [comment]
It can be fixed but these pose no problem to the menu and do not cause the menu to become unstable.

I haven't looked at how to fix it but I have a bunch of ideas on how to do it. Though it isn't a priority since this doesn't cause any problem.

**Comment by maybegreat48** [comment]
This is due to a race between native hooking and the call to `native_invoker::cache_handlers`. The hooked hander tries to call the original before the cache initializes (which it does on the first `script_mgr` tick which also requires `main_persistent` to be running). This issue will become more visible when the menu is injected while the game is starting. A fix is to cache natives exactly once in the run script threads hook instead

**Comment by Vali0004** [comment]
> This is due to a race between native hooking and the call to `native_invoker::cache_handlers`. The hooked hander tries to call the original before the cache initializes (which it does on the first `script_mgr` tick which also requires `main_persistent` to be running). This issue will become more visible when the menu is injected while the game is starting. A fix is to cache natives exactly once in the run script threads hook instead

Or, cache them once on runtime after pointer scan like a normal person.

**Comment by maybegreat48** [comment]
That won't work if the menu is loaded before the natives initialize

**Comment by Vali0004** [comment]
> That won't work if the menu is loaded before the natives initialize

The wonders that were publicly posted. Game state, along with other checks + patches

**Comment by maybegreat48** [comment]
Natives are initialized during the legal screens (usually), the native table is empty before that. Menus using DLL hijacking or just injected too soon will load long before that point. The native registration function is encrypted and will only be decrypted if certain DRM checks pass and therefore cannot be called or patched. The real reason why this issue exists is because `main_persistent` is not the first script started by the engine (that would be `startup`). We simply move the `cache_handlers` call up the call stream over to the `run_script_threads` hook which will cause the natives to be cached during the first tick. I mean yes you can try to hook the native registration somehow but that will just be an extra pattern+hook

**Comment by Vali0004** [comment]
> Natives are initialized during the legal screens (usually), the native table is empty before that. Menus using DLL hijacking or just injected too soon will load long before that point. The native registration function is encrypted and will only be decrypted if certain DRM checks pass and therefore cannot be called or patched. The real reason why this issue exists is because `main_persistent` is not the first script started by the engine (that would be `startup`). We simply move the `cache_handlers` call up the call stream over to the `run_script_threads` hook which will cause the natives to be cached during the first tick. I mean yes you can try to hook the native registration somehow but that will just be an extra pattern+hook

Of course. It’s not hard to ensure legals have successfully passed checks. I’m talking about a form of game state check, ensure it’s in the main menu, and cache. The reason I think doing it in the RST hook is a terrible idea because it would require some way of executing once, which was done in the fiber system (stock BBv2) yet this issue still persists because it re-caches it each few ticks if something is missing. That causes a issue with where before native execution finishes, the natives get cached which means a failed to invoke because the handler doesn’t exist in the map yet.

**Comment by maybegreat48** [comment]
This is how I do it
```c++
void native_invoker::cache_handlers()
{
        if (m_handlers_cached)
		return;

	for (const rage::scrNativeMapping& mapping : g_crossmap)
	{
		rage::scrNativeHandler handler = g_pointers->m_get_native_handler(
			g_pointers->m_native_registration_table, mapping.second);
		m_handler_cache.emplace(mapping.first, handler);
	}

	m_handlers_cached = true;
}

bool hooks::run_script_threads(std::uint32_t ops_to_execute)
{
	g_native_invoker.cache_handlers();

	if (g_running)
	{
		g_script_mgr.tick();
	}

	return g_hooking->m_run_script_threads_hook.get_original<functions::run_script_threads_t>()(ops_to_execute);
}

```
Function is called every tick but the natives cache just once because of the bool guard. Run script threads is guaranteed to be called only after the natives initialize so the main menu check isn't required

**Comment by Vali0004** [comment]
> This is how I do it
> 
> ```c++
> void native_invoker::cache_handlers()
> {
>         if (m_handlers_cached)
> 		return;
> 
> 	for (const rage::scrNativeMapping& mapping : g_crossmap)
> 	{
> 		rage::scrNativeHandler handler = g_pointers->m_get_native_handler(
> 			g_pointers->m_native_registration_table, mapping.second);
> 		m_handler_cache.emplace(mapping.first, handler);
> 	}
> 
> 	m_handlers_cached = true;
> }
> 
> bool hooks::run_script_threads(std::uint32_t ops_to_execute)
> {
> 	g_native_invoker.cache_handlers();
> 
> 	if (g_running)
> 	{
> 		g_script_mgr.tick();
> 	}
> 
> 	return g_hooking->m_run_script_threads_hook.get_original<functions::run_script_threads_t>()(ops_to_execute);
> }
> ```
> 
> Function is called every tick but the natives cache just once because of the bool guard. Run script threads is guaranteed to be called only after the natives initialize so the main menu check isn't required

I simply cache them after the sig scan with some safety guards, I have game state checks because of how my D3DRenderer works so I don’t have to worry about that. I store some data related to the active thread, and that’s how I execute natives in a dx thread. What that means is I have to ensure those aren’t null otherwise everything breaks. Also, I don’t use the get handler function, I use the native registration table and loop through its entry system. Requires one sig and safety checks are done there.

**Comment by xiaoxiao921** [comment]
Looks like in the  OP case with the is_dlc_present native hash fail its because the native hooker is init before our native cache is available (because it get init before hooking is enabled, pr coming up
