### ISSUE TITLE
Crashing on inject

### ISSUE THREAD

**Issue by LukluA** [Yimura/YimMenu#46]
Crashing on inject tried 3 injectors

**Comment by Yimura** [comment]
![Meme](https://user-images.githubusercontent.com/24669514/149618398-640e2e3c-d34a-40c2-a889-42057ececbcc.jpg)

Please give more information, that's why the ISSUE TEMPLATES exist. I can do literally NOTHING with this issue.

Give me the names of the injectors used.
Did you modify YimMenu?
Which version of GTA V do you have (Steam/Epic/Rockstar Launcher)?
Were you ever successful or did it always crash?

**Comment by ThatKakiGuy** [comment]
Also give screenshots of error messages if there are any.

**Comment by Yimura** [comment]
@LukluA please make sure you contribute to the issue after opening it, I will close this issue in 12h, you're free to send a message about your issue and I'll reopen it.

**Comment by Yimura** [comment]
I will be closing your issue if you have any info to add you can just comment here and I'll reopen it.
