### ISSUE TITLE
[Bug]: Developer mode doesn't seem to work

### ISSUE THREAD

**Issue by fangshun2004** [Yimura/YimMenu#463]
### Describe the bug

I turned on dev_dlc in settings, there is no hidden developer mode in the online menu, and there is no r* developer t-shirt in the clothing store unlocked clothing.

### Steps To Reproduce

After opening the menu Go to Settings checked dev_dlc the content of the dve_dlc does not appear

### Expected Behavior

After turning on developer mode, developer T-shirts should appear in the clothing store. The Hidden Menu option appears in the online menu.
![20221001192105](https://user-images.githubusercontent.com/49193927/193407242-3e23bccd-bd52-4c24-b12e-fab18cea92b9.jpg)
![20221001192131](https://user-images.githubusercontent.com/49193927/193407261-f622664a-7895-45c4-a502-48f2be9c5c47.jpg)
However, after the actual opening, no clothes appeared in the clothing store
![20221001192143](https://user-images.githubusercontent.com/49193927/193407288-c2293811-5b8a-4c47-9ced-2f5fd71cb373.jpg)

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
There's a dev menu in settings? Could you link me to a video of said menu, I've never seen that before.

**Comment by xiaoxiao921** [comment]
I managed to find the r* dev shirts in the ponsonbys shop, in the unlock submenu, with current YimMenu, could you give more details?

**Comment by FIying-Scotsman** [comment]
The blank entry is the dev's "join via SCTV" option which doesn't work and I don't believe has ever worked since this hook was first used. You _can_ however RID join a session in SCTV mode (by giving the join command the right join type) which would do the same thing.

There's another blank entry somewhere (in the interaction menu maybe?) which was used by the devs to drop/create crate drop zones back on the PS3/360 era but that too never worked and was replaced with business battles on the current gen.

@fangshun2004 The dev shirts should be under "Special" if I remember correctly.

**Comment by maybegreat48** [comment]
Perhaps disabling whatever menu you used to get the first two screenshots can help

The Dev DLC afaik contains code and text files for the mission and freemode creators, spoofing it will allow the option to enter mission creator but it will reset constantly as the default mission creator is just a stub. The SCTV option is not a stub and works fine for me, may have to spoof `NETWORK_PLAYER_IS_ROCKSTAR_DEV` as well

I got into a strange interaction submenu a while ago named "Fireworks", not sure if that is what you are mentioning though

**Comment by FIying-Scotsman** [comment]
> Perhaps disabling whatever menu you used to get the first two screenshots can help
> 
> The Dev DLC afaik contains code and text files for the mission and freemode creators, spoofing it will allow the option to enter mission creator but it will reset constantly as the default mission creator is just a stub. The SCTV option is not a stub and works fine for me, may have to spoof `NETWORK_PLAYER_IS_ROCKSTAR_DEV` as well
> 
> I got into a strange interaction submenu a while ago named "Fireworks", not sure if that is what you are mentioning though

The fireworks submenu sounds very similar. The crate dropping option was from the 360/PS3 days and I believe it was similar to the freemode creator where the devs could drop a flare for an event crate to spawn at (probably to test the feature) but it never worked or made it across to the PC. I don't believe anyone actually got it working so it was mostly figured out through snippets here and there.

It sounds like the fireworks submenu may have replaced it as it would function very similarly (instead of a flare, it would spawn a firework at your position instead).

**Comment by Yimura** [comment]
Closing this issue as the dev DLC feature is working as intended.

If there are further questions regarding this issue, please respond below, I will reopen if necessary.
