### ISSUE TITLE
Release a dll or update the compiling tutorial

### ISSUE THREAD

**Issue by Rrhyast** [Yimura/YimMenu#54]
compiling tutorial is so complicated

**Comment by Yimura** [comment]
1. I'm not allowed to release a DLL due to UnknownCheats guidelines as I could create an infected DLL on Github and they can't check if it stays unmodified.

Ref.: https://www.unknowncheats.me/forum/3342210-post4.html

2. The tutorial is already copy paste I don't know how much easier you want me to make it. For reference the original BigBaseV2 doesn't even have anything more than the git clone commands and the GenerateProjects.bat file.
