### ISSUE TITLE
YimMenu has been detected by the sigscanner!

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#631]
It appears YimMenu has been detected by the sigscanner.
## How?
GTA has started using a new sigscanner and as such we cannot pinpoint what exactly is triggering the AC.
Thus, the old sigscanner we used in our Nightly build should no longer be trusted.

## Crash Log

```cpp
RAX: 0x1
RCX: 0x7FFA40503D44
RDX: 0x0
RBX: 0x2AA88F2A5E0
RSI: 0x12
RDI: 0x2AA973A8430
RSP: 0xEAC35E7A70
RBP: 0xEAC35FFAF0
R8:  0xEAC35E7A08
R9:  0x0
R10: 0x0
R11: 0x246
R12: 0xEAC35E7AF0
R13: 0x7FF6DAE13DC0
R14: 0x0
R15: 0x0

stack dump [0]	 GTA5.exe+0xA90D0B 0x7FF6D8D50D0B
stack dump [1]	 GTA5.exe+0xA90BFB 0x7FF6D8D50BFB
stack dump [2]	 GTA5.exe+0x12BC7F2 0x7FF6D957C7F2
stack dump [3]	 GTA5.exe+0x12C5642 0x7FF6D9585642
stack dump [4]	 KERNEL32.DLL+0x15550 BaseThreadInitThunk
stack dump [5]	 ntdll.dll+0x485B RtlUserThreadStart
```

### Alternative Crash Log
Same sigscanner but different system

```cpp
RAX: 0x1
RCX: 0x7FFA04A51804
RDX: 0x0
RBX: 0x167D6FBA660
RSI: 0x12
RDI: 0x167E6EBA970
RSP: 0x291BCE7920
RBP: 0x291BCFF9A0
R8:  0x291BCE78B8
R9:  0x0
R10: 0x0
R11: 0x246
R12: 0x291BCE79A0
R13: 0x7FF6C7B13DC0
R14: 0x0
R15: 0x0

stack dump [0]	 GTA5.exe+0xA90D0B 0x7FF6C5A50D0B
stack dump [1]	 GTA5.exe+0xA90BFB 0x7FF6C5A50BFB
stack dump [2]	 GTA5.exe+0x12BC7F2 0x7FF6C627C7F2
stack dump [3]	 GTA5.exe+0x12C5642 0x7FF6C6285642
stack dump [4]	 KERNEL32.DLL+0x1335D BaseThreadInitThunk
stack dump [5]	 ntdll.dll+0x67558 RtlUserThreadStart
```

## Identify

Easiest way to identify if a crash is caused by the sigscanner is looking at the stack dump, if you see `GTA5.exe+0xA90D0B`, you can be sure it's the sigscanner.
The register dump is in both cases very similar.

**Comment by AtomBottle** [comment]
iused vmp protect void"EnityPoint" will it got ban?

**Comment by Aure7138** [comment]
I guess this doesn't prevent integrity checks, but maybe sigscan, yes

EDIT: Just replying to some guy who deleted his comment @AtomBottle

**Comment by ghost** [comment]
So the sig scanner crashes the menu now instead of detecting you? What is the exception code?

**Comment by MarkEcza** [comment]
> 
> 
> I guess this doesn't prevent integrity checks, but maybe sigscan, yes

Don't think it would, since it gets unpacked when injected. Correct me if i'm wrong.

**Comment by Aure7138** [comment]
In my impression, if you use VMP correctly, even if you unpacked it, it will still vm the place you want to protect. I may be wrong

**Comment by AtomicBool** [comment]
How about use VMProtectcon.exe i dont know about the new sigscanner . correct me if i'm wrong

**Comment by FIying-Scotsman** [comment]
> How about use VMProtectcon.exe i dont know about the new sigscanner . correct me if i'm wrong

VMP is designed to obfuscate binaries at rest and to make it harder to reverse engineer. It won’t protect you from pulling out identifying code in memory which is what the sig scanner does. 

It’s too early to say how the new scanner works but the previous iteration would search pages for a list of strings and would do a couple of other checks if it found a result.

Even if you obfuscated the strings using a simple XOR (so it would be garbled at rest) but you left open a page in your menu with the detected string - it would be picked up as it would be de-obfuscated to show you the “real” string instead of the obfuscated one, which would then be picked up by the scanner.  A similar thing happened with VMP as they could just start looking for VMP specific strings or catch you while the string was being displayed (even though it would be run via VMP’s VM - it’s still sitting in a buffer somewhere to be shown on your screen).

**Comment by DaniTRDev** [comment]
They can also specifically start sigging VMP or any other VMer (I think EAC/ BE does this already?). There are multiple sigs that can be used to trace any of these 'new gen' packers.

**Comment by DaniTRDev** [comment]
I've looked through the crash point and it seems that the menu is messing around with Arxan rather than being detected by the sigscanner.
