### ISSUE TITLE
[Request]: Asynchronous signature scanning

### ISSUE THREAD

**Issue by Vali0004** [Yimura/YimMenu#657]
### Problem

N/A

### Solution

N/A

### Reason

I'd like to have async signature scanning because the scan time would drastically decrease. It's not exactly needed but I think it'd be nice

### Store
Epic Games

### Build
- [x] I used YimMenu unmodified

**Comment by Aure7138** [comment]
Enabling the hook still needs to wait for the signature scan to end. If you want the signature scan to be faster, caching the scan results may be better than asynchronous

**Comment by Vali0004** [comment]
> Enabling the hook still needs to wait for the signature scan to end. If you want the signature scan to be faster, caching the scan results may be better than asynchronous

Not really. Also, creating a good and speedy caching system is much harder than utilizing the thread pool in a certain manner

**Comment by ghost** [comment]
I will never understand your hard-on for shorter sigs and asynchronous sig scanning, you want to spin up 10 different scanning threads while you set up the menu and rape peoples' CPUs for the sake of NOT caching the results of a scan that will *always* be the same unless the game updates?

Caching results would not only be simple, it would be light and even faster than asynchronous scanning after the first injection.

Just distinguish game builds via timestamp, and do the exact same thing for menu builds. If you inject a menu build that's never been injected before or you find a gta build you don't have a cache for, you run the pattern scan. Otherwise you just load up a JSON dump of the data on disk, which will be near instant.

If we want to be cynical about it, you could still load the results of the scan on disk if only the menu's build changed, and only scan for the patterns that are missing / that you just added.

Result caching is the superior solution that works for everyone's machines.
