### ISSUE TITLE
[Bug]: UI Scale is not implemented properly

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#749]
### Describe the bug

UI scale does not work the way that UI scaling is supposed to

### Steps To Reproduce

1. Set UI scale to 1.50, click apply
2. Set UI scale back to 1.0, click apply
3. Repeat
4. Nonsense

### Expected Behavior

The UI resolution and aspect ratio are able to revert to their original size and ratio, and the scale of the menu should maintain aspect ratio

### Screenshots and/or Logs

https://www.youtube.com/watch?v=3cDGXgSlQn4

### Store

Steam

### Additional context

HELLO ASPECT RATIO IS A THING

Used latest nightly build as of 12/24

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
I believe there's a tooltip that mentions you may be required to unload and load YimMenu again.
It's not really our implementation of lt that's wrong because we're literally using ImGui's official scaling methods.
https://github.com/YimMenu/YimMenu/blob/54b3267537e3bf07f97d6a0ddb59aacf0a54d0c1/src/views/settings/view_gui_settings.cpp#L11-L14
I'd expect someone would only ever need to rescale their UI once and never again, so this is not an issue I plan on fixing.

Closing as there's a tooltip that says you may need to unload YimMenu when changing the scale.
