### ISSUE TITLE
masm error on DEFAULT YIM MENU

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#786]
![image](https://user-images.githubusercontent.com/67609719/210117703-92e48300-1f46-4b10-903d-8938a9875d27.png)
look at the project name and path.

**Comment by ghost** [comment]
bro what?

**Comment by Loko415** [comment]
its a masm error

**Comment by Loko415** [comment]
cannot find ml64.exe in path

**Comment by ghost** [comment]
Didn't they like just tell you, they wouldn't help you?
They closed your previous issue, just for you to open it again...

**Comment by Loko415** [comment]
they wouldnt help me because it wasnt unmodified yim menu. Now it is

**Comment by ghost** [comment]
No, you literally just renamed your previous skidproject.

**Comment by BugisoftRSG** [comment]
I will just tell you only one time ok?
We dont give single fuck about your menu promotheus or eclipse menu idk which one you really own. But I know you are on a weird discord server with idiots. And your issues are a demand on something you YOU DONT have and how about you take your skidded menu with your weirdos and put it deep in your asshole? 
![image](https://user-images.githubusercontent.com/58910128/210117870-6c6b3462-9aed-4859-8b28-4c0986f67519.png)
It doesnt matter what your problem is you are just arrogant and think you are the mighty "Professional c++ coding monkey" 
The only thing you did was a launcher in python great... you are not better than radic menu, eclipse menu, promotheus, what so ever just get normal which will obv not gonna happen or get out of here and make your own menu. This is not a basar for wasting our time with some issues you got with your copied thing and your model crasher you can also put somewhere...

**Comment by secret-stash** [comment]
> I will just tell you only one time ok? We dont give single fuck about your menu promotheus or eclipse menu idk which one you really own. But I know you are on a weird discord server with idiots. And your issues are a demand on something you YOU DONT have and how about you take your skidded menu with your weirdos and put it deep in your asshole? ![image](https://user-images.githubusercontent.com/58910128/210117870-6c6b3462-9aed-4859-8b28-4c0986f67519.png) It doesnt matter what your problem is you are just arrogant and think you are the mighty "Professional c++ coding monkey" The only thing you did was a launcher in python great... you are not better than radic menu, eclipse menu, promotheus, what so ever just get normal which will obv not gonna happen or get out of here and make your own menu. This is not a basar for wasting our time with some issues you got with your copied thing and your model crasher you can also put somewhere...

How did my comment get deleted, and yours didn't?

**Comment by Loko415** [comment]
well check credits

**Comment by Loko415** [comment]
why are you so mad? 💀

**Comment by Loko415** [comment]
if you have any issues on credits i legit say if you want credits DM ME

**Comment by Loko415** [comment]
> I will just tell you only one time ok? We dont give single fuck about your menu promotheus or eclipse menu idk which one you really own. But I know you are on a weird discord server with idiots. And your issues are a demand on something you YOU DONT have and how about you take your skidded menu with your weirdos and put it deep in your asshole? ![image](https://user-images.githubusercontent.com/58910128/210117870-6c6b3462-9aed-4859-8b28-4c0986f67519.png) It doesnt matter what your problem is you are just arrogant and think you are the mighty "Professional c++ coding monkey" The only thing you did was a launcher in python great... you are not better than radic menu, eclipse menu, promotheus, what so ever just get normal which will obv not gonna happen or get out of here and make your own menu. This is not a basar for wasting our time with some issues you got with your copied thing and your model crasher you can also put somewhere...

wtf did i do or say to you? notice how its free and it has a CREDITS CHANNEL. something radic nor spectrum has and we all know how much they skid

**Comment by BugisoftRSG** [comment]
The GNU General Public License v2.0 requires you to disclose the source code to menus which are based yimmenu. For more information: https://github.com/YimMenu/YimMenu/blob/master/LICENSE

**Comment by Yimura** [comment]
@Loko415 seems like an issue with your Visual Studio installation, please verify it.
Anyone with a full installation of C++ for desktop development should work for YimMenu.
