### ISSUE TITLE
[Request]: /help

### ISSUE THREAD

**Issue by CRGBS** [Yimura/YimMenu#788]
### Problem

/help to know command list

### Solution

just /help or something let we know what command can use

### Reason

more ez for use

**Comment by ghost** [comment]
There is no such command gui atm. We only have the backend and some buttons.

**Comment by TheGreenBandit** [comment]
I think what we could do is have /help pull up a new window using ImGui::Begin and in that we put it like this

Command List

Self
Gm = godmode
fastrun = superrun
------------------ (Imgui::Separator)
Vehicle
vehfly = vehicle fly

**Comment by tupoy-ya** [comment]
Having `help` command open a gui doesn't make much sense to me.
1. How would you go about implementing this in chat?
2. How would you go about implementing command specific help ex. `help noclip`?
3. Why not just print commands in console when you use `help`.

**Comment by ghost** [comment]
I think stands command implementation is perfect. Auto-generating command list that can be hosted on GitHub. No need for a help
Command

**Comment by tupoy-ya** [comment]
Help command is still useful in chat or if you don't want to search for online documentation.

**Comment by ghost** [comment]
I don't think using chat or the console is a good way to get/display commands. Creating a window would be good imo.

**Comment by tupoy-ya** [comment]
Well i just don't like gui i guess, it's bloated enough already and when you have a console, header, menu selector, player list, and a currently selected window you don't have a lot of screen space left.

**Comment by ghost** [comment]
It is bloated. But the window will be designed to find a command and close it. In the end it's up to yim and whoever does it.

**Comment by TheGreenBandit** [comment]
i mean i was just thinking my way as a way to solve it quickly

**Comment by FIying-Scotsman** [comment]
> i mean i was just thinking my way as a way to solve it quickly

With a project the size of Yimmenu - you have to plan ahead otherwise it comes back to bite you at the worst time in the future.

As others have mentioned, it may be quick to you but in reality - it would need maintaining (adding future commands for example) and any windows would need to be created and put somewhere on the screen so depending on your resolution - you could end up with Yimmenu UI components literally covering the game's window.

Personally I'd follow in the footsteps of Source engine games - 1 window for logging with an option to input commands similar to a Terminal/command prompt window. It keeps everything under 1 box which you can easily scroll if you missed something and also means we don't have to add new UI components when we can just reuse an existing one.
