### ISSUE TITLE
[Request]: Modder detection reason in playerlist

### ISSUE THREAD

**Issue by LiamD-Flop** [Yimura/YimMenu#853]
### Problem

When a modder gets detected it's annoying to have to go to the player database and find them in there to see why they got detected.

### Solution

Add the reason to the player info or at the top of the player tab so you can quickly see why they got flagged.

### Reason

I'm retarded and always open the player to find out why they are flagged. And can't seem to quickly find them inside the player database.

**Comment by ghost** [comment]
There's a few things in this menu that were designed by an actual monkey. Impossible for a human to utilize quickly and efficiently. Summarizes this entire hack.

**Comment by Yimura** [comment]
The one that made this issue is the one that designed the current UI.
He's very much aware of it, the UI was sadly designed way back when there was no real thinking behind if it was a good idea to design the UI this way.
Anyways, we've been thinking about doing the UI differently for some time now.

**Comment by ghost** [comment]
What? The UI is fine. Just remove all the dropdown lists and make it so I don't have to scroll for a thousand pages. Also maybe make the main and sub tabs consistent. 

Example: Clicking on "Self" main tab opens options but clicking on "Network" main tab does nothing. Clicking on "Network" should just show what "Session" shows.

Also "Protections" is in settings instead of "Network". 

This whole menu needs to be reorganized. I did this a while ago but the fork is months outdated.

**Comment by LiamD-Flop** [comment]
We know the UI is not organised. I've been complaining for it for a while. When designing this UI we also didn't have this amount of features. Also we copied the layout from the UI before that. I would say that the current problem is that there is no thought process on how the features are organised. Anyways I think this is a different issue not really related to the struggle I'm having here 😅
