### ISSUE TITLE
[Bug]: liam d flop owes me a new gta account

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#885]
### Describe the bug

proceeded to "corrupt my gta save" using an exploit in "private yim menu" if you really are a "liberal no recovery mod menu #notoxicletsallgetalong then why do you have a retard contributor running around like a sped corrupting innocent peoples saves? seems like he targetted me because of my fork of YIM MENU and because of how my fork of YIM MENU violates everything you "stand for" having recovery and drops etc. I dont understand what problems you have with me or what petty opinions you have on me just stop joining my server and clowning my shit. At this point just leave me alone im sick of dealing with all of you and your contributors. You act like you are underage and retarded. Coming from someone who is 15 myself you act more immature then me.

### Steps To Reproduce

1. make a yim menu fork
2. add skidded / drops
3. make it popular
4. get harassed by contributors
5. quit because of contributors
6. fuck you

### Expected Behavior

leave me alone

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Loko415** [comment]
https://www.reddit.com/r/Gta5Modding/comments/10ej123/to_all_those_wrongly_put_in_bad_sport/

**Comment by gypsiecrusadrr** [comment]
![maxresdefault-128](https://user-images.githubusercontent.com/86495505/213502419-a006b88c-21d3-4f4a-b185-84144d2646c8.jpg)

**Comment by JDMJay** [comment]
bugi if your that stupid here's some simpler information 
1. "Harvey" asked him to join his game 
2. He joined
3. "Harvey" kept putting him in bad sport
4. "Loko" kept removing the bad sport
5. "Harvey" resorts to using "private yimmenu" code to fuck his game save 
6. "Loko" makes a pr
7. "Bugisoft" I am stupid I cannot read.

**Comment by Loko415** [comment]
^

**Comment by Loko415** [comment]
@Yimura fix your shit... im done

**Comment by yasmasdas** [comment]
Should this not be resolved in private? Nothing to do with yimuras menu really

**Comment by Loko415** [comment]
it is considering he has these kinds of people having access to this kind of stuff

**Comment by yasmasdas** [comment]
Not a issue with yimmenu right? since it's a private matter

**Comment by JDMJay** [comment]
> Not a issue with yimmenu right? since it's a private matter

It is an issue with yimmenu, shitty rebound dev should not be a contributor as he's just causing "issues"

**Comment by LiamD-Flop** [comment]
Let's break this down:
1. This indeed seems to be a private issue which Loko insists YimMenu contributors are to blame for
2. I don't see why you're upholding the same rules to a "private" version on YimMenu. The same rules you're breaking yourself with your "private" version of YimMenu.
3. It's not because a lobby has everyone named YimMenu that one of the contributors is the one doing it. It's a default feature in YimMenu to do this so anyone is able to spoof names like it.
4. I don't see why I would owe you a new gta account, yes I posted a session token to your discord. But does that mean that it was my token /  I forced you to join / actually did something to you?

**Comment by Yimura** [comment]
1. This is not an issue with YimMenu
2. Harvey or rather "The Rebound Dev" does not contribute to YimMenu
3. Anyone can modify YimMenu and add their own stuff to it (you're technically in violation of the license because you don't provide the source code)

Anyways all you're doing is giving free publicity for Rebound Menu.
Also hereby @Loko415 is permanently banned and I've enabled interaction limits on the repository for new accounts until this has cooled down.

**Comment by BugisoftRSG** [comment]
Pogchamp

**Comment by LiamD-Flop** [comment]
![image](https://user-images.githubusercontent.com/40887493/213519764-6d940e0c-8fb4-4433-a79c-97629d64818a.png)

**Comment by ghost** [comment]
💀💀💀

**Comment by ghost** [comment]
cope harder loko boyyyyy

**Comment by BugisoftRSG** [comment]
![image](https://user-images.githubusercontent.com/58910128/213545582-76f1d586-9288-4782-a6f5-3a06a9e26628.png)

**Comment by BugisoftRSG** [comment]
![image](https://user-images.githubusercontent.com/58910128/213546016-f3853632-2be4-437f-92ae-f0078c36c88f.png)

**Comment by ghost** [comment]
gta source (colorized)
![maxresdefault-128](https://user-images.githubusercontent.com/86495505/213547225-aea33881-3a9f-48f3-8c9d-5fea70424351.jpg)
